//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H.Extensions.FFMpeg.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("H.Extensions.FFMpeg.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 多语言测试1.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你好2.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exe路径.
        /// </summary>
        public static string Property_FFMpegOption_BinaryFolder {
            get {
                return ResourceManager.GetString("Property_FFMpegOption_BinaryFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日志级别.
        /// </summary>
        public static string Property_FFMpegOption_FFMpegLogLevel {
            get {
                return ResourceManager.GetString("Property_FFMpegOption_FFMpegLogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 缓存路径.
        /// </summary>
        public static string Property_FFMpegOption_TemporaryFilesFolder {
            get {
                return ResourceManager.GetString("Property_FFMpegOption_TemporaryFilesFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用缓存.
        /// </summary>
        public static string Property_FFMpegOption_UseCache {
            get {
                return ResourceManager.GetString("Property_FFMpegOption_UseCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用多线程.
        /// </summary>
        public static string Property_FFMpegOption_UsingMultithreading {
            get {
                return ResourceManager.GetString("Property_FFMpegOption_UsingMultithreading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工作路径.
        /// </summary>
        public static string Property_FFMpegOption_WorkingDirectory {
            get {
                return ResourceManager.GetString("Property_FFMpegOption_WorkingDirectory", resourceCulture);
            }
        }
    }
}
