//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H.App.FileManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("H.App.FileManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 多语言测试1.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你好2.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 布局方式.
        /// </summary>
        public static string Property_AppSetting_DisplayMode {
            get {
                return ResourceManager.GetString("Property_AppSetting_DisplayMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 缩率图拉伸方式.
        /// </summary>
        public static string Property_AppSetting_Stretch {
            get {
                return ResourceManager.GetString("Property_AppSetting_Stretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用工程管理.
        /// </summary>
        public static string Property_AppSetting_UseProject {
            get {
                return ResourceManager.GetString("Property_AppSetting_UseProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 缩率图尺寸.
        /// </summary>
        public static string Property_AppSetting_ViewSizeMode {
            get {
                return ResourceManager.GetString("Property_AppSetting_ViewSizeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用国家标记.
        /// </summary>
        public static string Property_FileProjectItemSetting_UseAreaTag {
            get {
                return ResourceManager.GetString("Property_FileProjectItemSetting_UseAreaTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用清晰度标记.
        /// </summary>
        public static string Property_FileProjectItemSetting_UseArticulationTag {
            get {
                return ResourceManager.GetString("Property_FileProjectItemSetting_UseArticulationTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用扩展名.
        /// </summary>
        public static string Property_FileProjectItemSetting_UseExtension {
            get {
                return ResourceManager.GetString("Property_FileProjectItemSetting_UseExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用喜欢过滤器.
        /// </summary>
        public static string Property_FileProjectItemSetting_UseFavorite {
            get {
                return ResourceManager.GetString("Property_FileProjectItemSetting_UseFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用收藏夹.
        /// </summary>
        public static string Property_FileProjectItemSetting_UseFavoritePath {
            get {
                return ResourceManager.GetString("Property_FileProjectItemSetting_UseFavoritePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用文件类型.
        /// </summary>
        public static string Property_FileProjectItemSetting_UseFileType {
            get {
                return ResourceManager.GetString("Property_FileProjectItemSetting_UseFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用历史记录.
        /// </summary>
        public static string Property_FileProjectItemSetting_UseHistory {
            get {
                return ResourceManager.GetString("Property_FileProjectItemSetting_UseHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用对象标记.
        /// </summary>
        public static string Property_FileProjectItemSetting_UseObjectTag {
            get {
                return ResourceManager.GetString("Property_FileProjectItemSetting_UseObjectTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用排序器.
        /// </summary>
        public static string Property_FileProjectItemSetting_UseOrderBox {
            get {
                return ResourceManager.GetString("Property_FileProjectItemSetting_UseOrderBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用像素格式.
        /// </summary>
        public static string Property_FileProjectItemSetting_UsePixelFormat {
            get {
                return ResourceManager.GetString("Property_FileProjectItemSetting_UsePixelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用评分.
        /// </summary>
        public static string Property_FileProjectItemSetting_UseScore {
            get {
                return ResourceManager.GetString("Property_FileProjectItemSetting_UseScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用稍后观看.
        /// </summary>
        public static string Property_FileProjectItemSetting_UseSeeLater {
            get {
                return ResourceManager.GetString("Property_FileProjectItemSetting_UseSeeLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用观看.
        /// </summary>
        public static string Property_FileProjectItemSetting_UseWatched {
            get {
                return ResourceManager.GetString("Property_FileProjectItemSetting_UseWatched", resourceCulture);
            }
        }
    }
}
