//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H.Modules.Feedback.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("H.Modules.Feedback.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用SSL.
        /// </summary>
        public static string Property_FeedbackOptions_EnableSsl {
            get {
                return ResourceManager.GetString("Property_FeedbackOptions_EnableSsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服务器.
        /// </summary>
        public static string Property_FeedbackOptions_Host {
            get {
                return ResourceManager.GetString("Property_FeedbackOptions_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用HTML格式.
        /// </summary>
        public static string Property_FeedbackOptions_IsBodyHtml {
            get {
                return ResourceManager.GetString("Property_FeedbackOptions_IsBodyHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 授权码.
        /// </summary>
        public static string Property_FeedbackOptions_Password {
            get {
                return ResourceManager.GetString("Property_FeedbackOptions_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 端口号.
        /// </summary>
        public static string Property_FeedbackOptions_Port {
            get {
                return ResourceManager.GetString("Property_FeedbackOptions_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外发账号.
        /// </summary>
        public static string Property_FeedbackOptions_User {
            get {
                return ResourceManager.GetString("Property_FeedbackOptions_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户反馈设置.
        /// </summary>
        public static string Type_FeedbackOptions {
            get {
                return ResourceManager.GetString("Type_FeedbackOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户反馈设置的信息.
        /// </summary>
        public static string Type_FeedbackOptions_Description {
            get {
                return ResourceManager.GetString("Type_FeedbackOptions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统设置.
        /// </summary>
        public static string Type_FeedbackOptions_GroupName {
            get {
                return ResourceManager.GetString("Type_FeedbackOptions_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户反馈.
        /// </summary>
        public static string Type_ShowFeedbackCommand {
            get {
                return ResourceManager.GetString("Type_ShowFeedbackCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示用户反馈页面.
        /// </summary>
        public static string Type_ShowFeedbackCommand_Description {
            get {
                return ResourceManager.GetString("Type_ShowFeedbackCommand_Description", resourceCulture);
            }
        }
    }
}
