// <auto-generated />
#nullable enable

using H.Styles.Controls;
using System;
using System.Globalization;
using System.Resources;

namespace H.Test.Globalization.Properties
{
    public static partial class Resources
    {
        private static ResourceManager? resourceMan;
        private static CultureInfo? resourceCulture;

        public static ResourceManager ResourceManager => resourceMan ??= new ResourceManager("H.Test.Globalization.Properties.Resources", typeof(Resources).Assembly);

        internal static CultureInfo? Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        public static string AppTitle => ResourceManager.GetString(nameof(AppTitle), resourceCulture) ?? nameof(AppTitle);
        public static string Hello => ResourceManager.GetString(nameof(Hello), resourceCulture) ?? nameof(Hello);
    }
}
