//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H.Globalization.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("H.Globalization.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中止.
        /// </summary>
        public static string Common_Abort {
            get {
                return ResourceManager.GetString("Common_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        public static string Common_About {
            get {
                return ResourceManager.GetString("Common_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 访问被拒绝.
        /// </summary>
        public static string Common_AccessDenied {
            get {
                return ResourceManager.GetString("Common_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账号.
        /// </summary>
        public static string Common_Account {
            get {
                return ResourceManager.GetString("Common_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加.
        /// </summary>
        public static string Common_Add {
            get {
                return ResourceManager.GetString("Common_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全部.
        /// </summary>
        public static string Common_All {
            get {
                return ResourceManager.GetString("Common_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应用.
        /// </summary>
        public static string Common_Apply {
            get {
                return ResourceManager.GetString("Common_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你确定吗？.
        /// </summary>
        public static string Common_AreYouSure {
            get {
                return ResourceManager.GetString("Common_AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 返回.
        /// </summary>
        public static string Common_Back {
            get {
                return ResourceManager.GetString("Common_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全选.
        /// </summary>
        public static string Common_CheckAll {
            get {
                return ResourceManager.GetString("Common_CheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检查更新.
        /// </summary>
        public static string Common_CheckForUpdates {
            get {
                return ResourceManager.GetString("Common_CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清除.
        /// </summary>
        public static string Common_Clear {
            get {
                return ResourceManager.GetString("Common_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭.
        /// </summary>
        public static string Common_Close {
            get {
                return ResourceManager.GetString("Common_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认.
        /// </summary>
        public static string Common_Confirm {
            get {
                return ResourceManager.GetString("Common_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认提示.
        /// </summary>
        public static string Common_Confirmation {
            get {
                return ResourceManager.GetString("Common_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定要删除吗？.
        /// </summary>
        public static string Common_ConfirmDelete {
            get {
                return ResourceManager.GetString("Common_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定要退出吗？.
        /// </summary>
        public static string Common_ConfirmExit {
            get {
                return ResourceManager.GetString("Common_ConfirmExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认密码.
        /// </summary>
        public static string Common_ConfirmPassword {
            get {
                return ResourceManager.GetString("Common_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否保存更改？.
        /// </summary>
        public static string Common_ConfirmSaveChanges {
            get {
                return ResourceManager.GetString("Common_ConfirmSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在连接....
        /// </summary>
        public static string Common_Connecting {
            get {
                return ResourceManager.GetString("Common_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复制.
        /// </summary>
        public static string Common_Copy {
            get {
                return ResourceManager.GetString("Common_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复制失败.
        /// </summary>
        public static string Common_CopyFailed {
            get {
                return ResourceManager.GetString("Common_CopyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复制成功.
        /// </summary>
        public static string Common_CopySucceeded {
            get {
                return ResourceManager.GetString("Common_CopySucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建.
        /// </summary>
        public static string Common_Create {
            get {
                return ResourceManager.GetString("Common_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 剪切.
        /// </summary>
        public static string Common_Cut {
            get {
                return ResourceManager.GetString("Common_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据库.
        /// </summary>
        public static string Common_DataBase {
            get {
                return ResourceManager.GetString("Common_DataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 默认.
        /// </summary>
        public static string Common_Default {
            get {
                return ResourceManager.GetString("Common_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        public static string Common_Delete {
            get {
                return ResourceManager.GetString("Common_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除选中.
        /// </summary>
        public static string Common_DeleteCheckAll {
            get {
                return ResourceManager.GetString("Common_DeleteCheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消全选.
        /// </summary>
        public static string Common_DeselectAll {
            get {
                return ResourceManager.GetString("Common_DeselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 禁用.
        /// </summary>
        public static string Common_Disable {
            get {
                return ResourceManager.GetString("Common_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在断开....
        /// </summary>
        public static string Common_Disconnecting {
            get {
                return ResourceManager.GetString("Common_Disconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载.
        /// </summary>
        public static string Common_Download {
            get {
                return ResourceManager.GetString("Common_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑.
        /// </summary>
        public static string Common_Edit {
            get {
                return ResourceManager.GetString("Common_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 空.
        /// </summary>
        public static string Common_Empty {
            get {
                return ResourceManager.GetString("Common_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用.
        /// </summary>
        public static string Common_Enable {
            get {
                return ResourceManager.GetString("Common_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误.
        /// </summary>
        public static string Common_Error {
            get {
                return ResourceManager.GetString("Common_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出.
        /// </summary>
        public static string Common_Exit {
            get {
                return ResourceManager.GetString("Common_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出.
        /// </summary>
        public static string Common_Export {
            get {
                return ResourceManager.GetString("Common_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 失败.
        /// </summary>
        public static string Common_Failed {
            get {
                return ResourceManager.GetString("Common_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 筛选.
        /// </summary>
        public static string Common_Filter {
            get {
                return ResourceManager.GetString("Common_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查找.
        /// </summary>
        public static string Common_Find {
            get {
                return ResourceManager.GetString("Common_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查找下一个.
        /// </summary>
        public static string Common_FindNext {
            get {
                return ResourceManager.GetString("Common_FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完成.
        /// </summary>
        public static string Common_Finish {
            get {
                return ResourceManager.GetString("Common_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 忘记密码.
        /// </summary>
        public static string Common_ForgotPassword {
            get {
                return ResourceManager.GetString("Common_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帮助.
        /// </summary>
        public static string Common_Help {
            get {
                return ResourceManager.GetString("Common_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 忽略.
        /// </summary>
        public static string Common_Ignore {
            get {
                return ResourceManager.GetString("Common_Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入.
        /// </summary>
        public static string Common_Import {
            get {
                return ResourceManager.GetString("Common_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示.
        /// </summary>
        public static string Common_Information {
            get {
                return ResourceManager.GetString("Common_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 插入.
        /// </summary>
        public static string Common_Insert {
            get {
                return ResourceManager.GetString("Common_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 格式不正确.
        /// </summary>
        public static string Common_InvalidFormat {
            get {
                return ResourceManager.GetString("Common_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入无效.
        /// </summary>
        public static string Common_InvalidInput {
            get {
                return ResourceManager.GetString("Common_InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 反选.
        /// </summary>
        public static string Common_InvertSelection {
            get {
                return ResourceManager.GetString("Common_InvertSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 共 {0} 项.
        /// </summary>
        public static string Common_ItemsCountFormat {
            get {
                return ResourceManager.GetString("Common_ItemsCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在加载....
        /// </summary>
        public static string Common_Loading {
            get {
                return ResourceManager.GetString("Common_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录.
        /// </summary>
        public static string Common_Login {
            get {
                return ResourceManager.GetString("Common_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出登录.
        /// </summary>
        public static string Common_Logout {
            get {
                return ResourceManager.GetString("Common_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网络错误.
        /// </summary>
        public static string Common_NetworkError {
            get {
                return ResourceManager.GetString("Common_NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建.
        /// </summary>
        public static string Common_New {
            get {
                return ResourceManager.GetString("Common_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下一步.
        /// </summary>
        public static string Common_Next {
            get {
                return ResourceManager.GetString("Common_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 否.
        /// </summary>
        public static string Common_No {
            get {
                return ResourceManager.GetString("Common_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暂无数据.
        /// </summary>
        public static string Common_NoData {
            get {
                return ResourceManager.GetString("Common_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 尚未实现.
        /// </summary>
        public static string Common_NotImplemented {
            get {
                return ResourceManager.GetString("Common_NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不支持.
        /// </summary>
        public static string Common_NotSupported {
            get {
                return ResourceManager.GetString("Common_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关.
        /// </summary>
        public static string Common_Off {
            get {
                return ResourceManager.GetString("Common_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定.
        /// </summary>
        public static string Common_Ok {
            get {
                return ResourceManager.GetString("Common_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开.
        /// </summary>
        public static string Common_On {
            get {
                return ResourceManager.GetString("Common_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开.
        /// </summary>
        public static string Common_Open {
            get {
                return ResourceManager.GetString("Common_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作失败.
        /// </summary>
        public static string Common_OperationFailed {
            get {
                return ResourceManager.GetString("Common_OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作成功.
        /// </summary>
        public static string Common_OperationSucceeded {
            get {
                return ResourceManager.GetString("Common_OperationSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选项.
        /// </summary>
        public static string Common_Options {
            get {
                return ResourceManager.GetString("Common_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 超出范围.
        /// </summary>
        public static string Common_OutOfRange {
            get {
                return ResourceManager.GetString("Common_OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第 {0} 页 / 共 {1} 页.
        /// </summary>
        public static string Common_PageFormat {
            get {
                return ResourceManager.GetString("Common_PageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码.
        /// </summary>
        public static string Common_Password {
            get {
                return ResourceManager.GetString("Common_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 粘贴.
        /// </summary>
        public static string Common_Paste {
            get {
                return ResourceManager.GetString("Common_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暂停.
        /// </summary>
        public static string Common_Pause {
            get {
                return ResourceManager.GetString("Common_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入.
        /// </summary>
        public static string Common_PleaseEnter {
            get {
                return ResourceManager.GetString("Common_PleaseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择.
        /// </summary>
        public static string Common_PleaseSelect {
            get {
                return ResourceManager.GetString("Common_PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请稍候....
        /// </summary>
        public static string Common_PleaseWait {
            get {
                return ResourceManager.GetString("Common_PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 偏好设置.
        /// </summary>
        public static string Common_Preferences {
            get {
                return ResourceManager.GetString("Common_Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 预览.
        /// </summary>
        public static string Common_Preview {
            get {
                return ResourceManager.GetString("Common_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上一步.
        /// </summary>
        public static string Common_Previous {
            get {
                return ResourceManager.GetString("Common_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打印.
        /// </summary>
        public static string Common_Print {
            get {
                return ResourceManager.GetString("Common_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示.
        /// </summary>
        public static string Common_Prompt {
            get {
                return ResourceManager.GetString("Common_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重做.
        /// </summary>
        public static string Common_Redo {
            get {
                return ResourceManager.GetString("Common_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷新.
        /// </summary>
        public static string Common_Refresh {
            get {
                return ResourceManager.GetString("Common_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册.
        /// </summary>
        public static string Common_Register {
            get {
                return ResourceManager.GetString("Common_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移除.
        /// </summary>
        public static string Common_Remove {
            get {
                return ResourceManager.GetString("Common_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重命名.
        /// </summary>
        public static string Common_Rename {
            get {
                return ResourceManager.GetString("Common_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 替换.
        /// </summary>
        public static string Common_Replace {
            get {
                return ResourceManager.GetString("Common_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 必填项.
        /// </summary>
        public static string Common_RequiredField {
            get {
                return ResourceManager.GetString("Common_RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重置.
        /// </summary>
        public static string Common_Reset {
            get {
                return ResourceManager.GetString("Common_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 继续.
        /// </summary>
        public static string Common_Resume {
            get {
                return ResourceManager.GetString("Common_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重试.
        /// </summary>
        public static string Common_Retry {
            get {
                return ResourceManager.GetString("Common_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        public static string Common_Save {
            get {
                return ResourceManager.GetString("Common_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 另存为.
        /// </summary>
        public static string Common_SaveAs {
            get {
                return ResourceManager.GetString("Common_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存失败.
        /// </summary>
        public static string Common_SaveFailed {
            get {
                return ResourceManager.GetString("Common_SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存成功.
        /// </summary>
        public static string Common_SaveSucceeded {
            get {
                return ResourceManager.GetString("Common_SaveSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 搜索.
        /// </summary>
        public static string Common_Search {
            get {
                return ResourceManager.GetString("Common_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择.
        /// </summary>
        public static string Common_Select {
            get {
                return ResourceManager.GetString("Common_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全选.
        /// </summary>
        public static string Common_SelectAll {
            get {
                return ResourceManager.GetString("Common_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已选择 {0} 项.
        /// </summary>
        public static string Common_SelectedCountFormat {
            get {
                return ResourceManager.GetString("Common_SelectedCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服务器错误.
        /// </summary>
        public static string Common_ServerError {
            get {
                return ResourceManager.GetString("Common_ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string Common_Settings {
            get {
                return ResourceManager.GetString("Common_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示.
        /// </summary>
        public static string Common_Show {
            get {
                return ResourceManager.GetString("Common_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排序.
        /// </summary>
        public static string Common_Sort {
            get {
                return ResourceManager.GetString("Common_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始.
        /// </summary>
        public static string Common_Start {
            get {
                return ResourceManager.GetString("Common_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止.
        /// </summary>
        public static string Common_Stop {
            get {
                return ResourceManager.GetString("Common_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功.
        /// </summary>
        public static string Common_Success {
            get {
                return ResourceManager.GetString("Common_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请求超时.
        /// </summary>
        public static string Common_Timeout {
            get {
                return ResourceManager.GetString("Common_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 合计.
        /// </summary>
        public static string Common_Total {
            get {
                return ResourceManager.GetString("Common_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未授权.
        /// </summary>
        public static string Common_Unauthorized {
            get {
                return ResourceManager.GetString("Common_Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 撤销.
        /// </summary>
        public static string Common_Undo {
            get {
                return ResourceManager.GetString("Common_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你有未保存的更改.
        /// </summary>
        public static string Common_UnsavedChanges {
            get {
                return ResourceManager.GetString("Common_UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新.
        /// </summary>
        public static string Common_Update {
            get {
                return ResourceManager.GetString("Common_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上传.
        /// </summary>
        public static string Common_Upload {
            get {
                return ResourceManager.GetString("Common_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名.
        /// </summary>
        public static string Common_UserName {
            get {
                return ResourceManager.GetString("Common_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看.
        /// </summary>
        public static string Common_View {
            get {
                return ResourceManager.GetString("Common_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 警告.
        /// </summary>
        public static string Common_Warning {
            get {
                return ResourceManager.GetString("Common_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 处理中....
        /// </summary>
        public static string Common_Working {
            get {
                return ResourceManager.GetString("Common_Working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是.
        /// </summary>
        public static string Common_Yes {
            get {
                return ResourceManager.GetString("Common_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应用.
        /// </summary>
        public static string Dialog_Button_Apply {
            get {
                return ResourceManager.GetString("Dialog_Button_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string Dialog_Button_Cancel {
            get {
                return ResourceManager.GetString("Dialog_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭.
        /// </summary>
        public static string Dialog_Button_Close {
            get {
                return ResourceManager.GetString("Dialog_Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 忽略.
        /// </summary>
        public static string Dialog_Button_Ignore {
            get {
                return ResourceManager.GetString("Dialog_Button_Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 否.
        /// </summary>
        public static string Dialog_Button_No {
            get {
                return ResourceManager.GetString("Dialog_Button_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定.
        /// </summary>
        public static string Dialog_Button_Ok {
            get {
                return ResourceManager.GetString("Dialog_Button_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重试.
        /// </summary>
        public static string Dialog_Button_Retry {
            get {
                return ResourceManager.GetString("Dialog_Button_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是.
        /// </summary>
        public static string Dialog_Button_Yes {
            get {
                return ResourceManager.GetString("Dialog_Button_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择文件夹.
        /// </summary>
        public static string Dialog_File_FolderTitle {
            get {
                return ResourceManager.GetString("Dialog_File_FolderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择要打开的文件.
        /// </summary>
        public static string Dialog_File_OpenTitle {
            get {
                return ResourceManager.GetString("Dialog_File_OpenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件已存在，是否覆盖？.
        /// </summary>
        public static string Dialog_File_OverwritePrompt {
            get {
                return ResourceManager.GetString("Dialog_File_OverwritePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择保存位置.
        /// </summary>
        public static string Dialog_File_SaveTitle {
            get {
                return ResourceManager.GetString("Dialog_File_SaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你确定吗？.
        /// </summary>
        public static string Dialog_Message_AreYouSure {
            get {
                return ResourceManager.GetString("Dialog_Message_AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定要删除吗？此操作无法撤销。.
        /// </summary>
        public static string Dialog_Message_ConfirmDelete {
            get {
                return ResourceManager.GetString("Dialog_Message_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定要退出吗？.
        /// </summary>
        public static string Dialog_Message_ConfirmExit {
            get {
                return ResourceManager.GetString("Dialog_Message_ConfirmExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前操作不受支持。.
        /// </summary>
        public static string Dialog_Message_NotSupported {
            get {
                return ResourceManager.GetString("Dialog_Message_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作失败。.
        /// </summary>
        public static string Dialog_Message_OperationFailed {
            get {
                return ResourceManager.GetString("Dialog_Message_OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作成功。.
        /// </summary>
        public static string Dialog_Message_OperationSucceeded {
            get {
                return ResourceManager.GetString("Dialog_Message_OperationSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你有未保存的更改，是否保存？.
        /// </summary>
        public static string Dialog_Message_UnsavedChanges {
            get {
                return ResourceManager.GetString("Dialog_Message_UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        public static string Dialog_Title_About {
            get {
                return ResourceManager.GetString("Dialog_Title_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认.
        /// </summary>
        public static string Dialog_Title_Confirm {
            get {
                return ResourceManager.GetString("Dialog_Title_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误.
        /// </summary>
        public static string Dialog_Title_Error {
            get {
                return ResourceManager.GetString("Dialog_Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示.
        /// </summary>
        public static string Dialog_Title_Information {
            get {
                return ResourceManager.GetString("Dialog_Title_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string Dialog_Title_Settings {
            get {
                return ResourceManager.GetString("Dialog_Title_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 警告.
        /// </summary>
        public static string Dialog_Title_Warning {
            get {
                return ResourceManager.GetString("Dialog_Title_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复制.
        /// </summary>
        public static string File_Copy {
            get {
                return ResourceManager.GetString("File_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建时间.
        /// </summary>
        public static string File_DateCreated {
            get {
                return ResourceManager.GetString("File_DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改时间.
        /// </summary>
        public static string File_DateModified {
            get {
                return ResourceManager.GetString("File_DateModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        public static string File_Delete {
            get {
                return ResourceManager.GetString("File_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无权限访问。.
        /// </summary>
        public static string File_Error_AccessDenied {
            get {
                return ResourceManager.GetString("File_Error_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已存在同名文件或文件夹。.
        /// </summary>
        public static string File_Error_AlreadyExists {
            get {
                return ResourceManager.GetString("File_Error_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未找到文件夹。.
        /// </summary>
        public static string File_Error_FolderNotFound {
            get {
                return ResourceManager.GetString("File_Error_FolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件正在使用中。.
        /// </summary>
        public static string File_Error_InUse {
            get {
                return ResourceManager.GetString("File_Error_InUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 路径无效。.
        /// </summary>
        public static string File_Error_InvalidPath {
            get {
                return ResourceManager.GetString("File_Error_InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未找到文件。.
        /// </summary>
        public static string File_Error_NotFound {
            get {
                return ResourceManager.GetString("File_Error_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 读取失败。.
        /// </summary>
        public static string File_Error_ReadFailed {
            get {
                return ResourceManager.GetString("File_Error_ReadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 写入失败。.
        /// </summary>
        public static string File_Error_WriteFailed {
            get {
                return ResourceManager.GetString("File_Error_WriteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所有文件 (*.*).
        /// </summary>
        public static string File_Filter_AllFiles {
            get {
                return ResourceManager.GetString("File_Filter_AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移动.
        /// </summary>
        public static string File_Move {
            get {
                return ResourceManager.GetString("File_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名称.
        /// </summary>
        public static string File_Name {
            get {
                return ResourceManager.GetString("File_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建文件.
        /// </summary>
        public static string File_NewFile {
            get {
                return ResourceManager.GetString("File_NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建文件夹.
        /// </summary>
        public static string File_NewFolder {
            get {
                return ResourceManager.GetString("File_NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开文件.
        /// </summary>
        public static string File_OpenFile {
            get {
                return ResourceManager.GetString("File_OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开文件夹.
        /// </summary>
        public static string File_OpenFolder {
            get {
                return ResourceManager.GetString("File_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 路径.
        /// </summary>
        public static string File_Path {
            get {
                return ResourceManager.GetString("File_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重命名.
        /// </summary>
        public static string File_Rename {
            get {
                return ResourceManager.GetString("File_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 还原.
        /// </summary>
        public static string File_Restore {
            get {
                return ResourceManager.GetString("File_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存全部.
        /// </summary>
        public static string File_SaveAll {
            get {
                return ResourceManager.GetString("File_SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存文件.
        /// </summary>
        public static string File_SaveFile {
            get {
                return ResourceManager.GetString("File_SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大小.
        /// </summary>
        public static string File_Size {
            get {
                return ResourceManager.GetString("File_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 类型.
        /// </summary>
        public static string File_Type {
            get {
                return ResourceManager.GetString("File_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        public static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检查更新.
        /// </summary>
        public static string Menu_CheckForUpdates {
            get {
                return ResourceManager.GetString("Menu_CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭.
        /// </summary>
        public static string Menu_Close {
            get {
                return ResourceManager.GetString("Menu_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全部关闭.
        /// </summary>
        public static string Menu_CloseAll {
            get {
                return ResourceManager.GetString("Menu_CloseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复制.
        /// </summary>
        public static string Menu_Copy {
            get {
                return ResourceManager.GetString("Menu_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 剪切.
        /// </summary>
        public static string Menu_Cut {
            get {
                return ResourceManager.GetString("Menu_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        public static string Menu_Delete {
            get {
                return ResourceManager.GetString("Menu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文档.
        /// </summary>
        public static string Menu_Documentation {
            get {
                return ResourceManager.GetString("Menu_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑.
        /// </summary>
        public static string Menu_Edit {
            get {
                return ResourceManager.GetString("Menu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出.
        /// </summary>
        public static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出.
        /// </summary>
        public static string Menu_Export {
            get {
                return ResourceManager.GetString("Menu_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 反馈.
        /// </summary>
        public static string Menu_Feedback {
            get {
                return ResourceManager.GetString("Menu_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件.
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查找.
        /// </summary>
        public static string Menu_Find {
            get {
                return ResourceManager.GetString("Menu_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查找下一个.
        /// </summary>
        public static string Menu_FindNext {
            get {
                return ResourceManager.GetString("Menu_FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全屏.
        /// </summary>
        public static string Menu_FullScreen {
            get {
                return ResourceManager.GetString("Menu_FullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帮助.
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入.
        /// </summary>
        public static string Menu_Import {
            get {
                return ResourceManager.GetString("Menu_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建.
        /// </summary>
        public static string Menu_New {
            get {
                return ResourceManager.GetString("Menu_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开.
        /// </summary>
        public static string Menu_Open {
            get {
                return ResourceManager.GetString("Menu_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最近打开.
        /// </summary>
        public static string Menu_OpenRecent {
            get {
                return ResourceManager.GetString("Menu_OpenRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 粘贴.
        /// </summary>
        public static string Menu_Paste {
            get {
                return ResourceManager.GetString("Menu_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 偏好设置.
        /// </summary>
        public static string Menu_Preferences {
            get {
                return ResourceManager.GetString("Menu_Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打印.
        /// </summary>
        public static string Menu_Print {
            get {
                return ResourceManager.GetString("Menu_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打印预览.
        /// </summary>
        public static string Menu_PrintPreview {
            get {
                return ResourceManager.GetString("Menu_PrintPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重做.
        /// </summary>
        public static string Menu_Redo {
            get {
                return ResourceManager.GetString("Menu_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷新.
        /// </summary>
        public static string Menu_Refresh {
            get {
                return ResourceManager.GetString("Menu_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 替换.
        /// </summary>
        public static string Menu_Replace {
            get {
                return ResourceManager.GetString("Menu_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重置缩放.
        /// </summary>
        public static string Menu_ResetZoom {
            get {
                return ResourceManager.GetString("Menu_ResetZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        public static string Menu_Save {
            get {
                return ResourceManager.GetString("Menu_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全部保存.
        /// </summary>
        public static string Menu_SaveAll {
            get {
                return ResourceManager.GetString("Menu_SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 另存为.
        /// </summary>
        public static string Menu_SaveAs {
            get {
                return ResourceManager.GetString("Menu_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全选.
        /// </summary>
        public static string Menu_SelectAll {
            get {
                return ResourceManager.GetString("Menu_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 切换侧边栏.
        /// </summary>
        public static string Menu_ToggleSidebar {
            get {
                return ResourceManager.GetString("Menu_ToggleSidebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 切换状态栏.
        /// </summary>
        public static string Menu_ToggleStatusBar {
            get {
                return ResourceManager.GetString("Menu_ToggleStatusBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工具.
        /// </summary>
        public static string Menu_Tools {
            get {
                return ResourceManager.GetString("Menu_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 撤销.
        /// </summary>
        public static string Menu_Undo {
            get {
                return ResourceManager.GetString("Menu_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 视图.
        /// </summary>
        public static string Menu_View {
            get {
                return ResourceManager.GetString("Menu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 窗口.
        /// </summary>
        public static string Menu_Window {
            get {
                return ResourceManager.GetString("Menu_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 放大.
        /// </summary>
        public static string Menu_ZoomIn {
            get {
                return ResourceManager.GetString("Menu_ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 缩小.
        /// </summary>
        public static string Menu_ZoomOut {
            get {
                return ResourceManager.GetString("Menu_ZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账号.
        /// </summary>
        public static string Nav_Account {
            get {
                return ResourceManager.GetString("Nav_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 返回.
        /// </summary>
        public static string Nav_Back {
            get {
                return ResourceManager.GetString("Nav_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仪表盘.
        /// </summary>
        public static string Nav_Dashboard {
            get {
                return ResourceManager.GetString("Nav_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 收藏.
        /// </summary>
        public static string Nav_Favorites {
            get {
                return ResourceManager.GetString("Nav_Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 历史记录.
        /// </summary>
        public static string Nav_History {
            get {
                return ResourceManager.GetString("Nav_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主页.
        /// </summary>
        public static string Nav_Home {
            get {
                return ResourceManager.GetString("Nav_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下一步.
        /// </summary>
        public static string Nav_Next {
            get {
                return ResourceManager.GetString("Nav_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通知.
        /// </summary>
        public static string Nav_Notifications {
            get {
                return ResourceManager.GetString("Nav_Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上一步.
        /// </summary>
        public static string Nav_Previous {
            get {
                return ResourceManager.GetString("Nav_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 个人资料.
        /// </summary>
        public static string Nav_Profile {
            get {
                return ResourceManager.GetString("Nav_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 项目.
        /// </summary>
        public static string Nav_Projects {
            get {
                return ResourceManager.GetString("Nav_Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最近.
        /// </summary>
        public static string Nav_Recent {
            get {
                return ResourceManager.GetString("Nav_Recent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安全.
        /// </summary>
        public static string Nav_Security {
            get {
                return ResourceManager.GetString("Nav_Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string Nav_Settings {
            get {
                return ResourceManager.GetString("Nav_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 访问被拒绝。.
        /// </summary>
        public static string Permission_AccessDenied {
            get {
                return ResourceManager.GetString("Permission_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 需要管理员权限。.
        /// </summary>
        public static string Permission_AdminRequired {
            get {
                return ResourceManager.GetString("Permission_AdminRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        public static string Permission_Delete {
            get {
                return ResourceManager.GetString("Permission_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 执行.
        /// </summary>
        public static string Permission_Execute {
            get {
                return ResourceManager.GetString("Permission_Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 授予.
        /// </summary>
        public static string Permission_Grant {
            get {
                return ResourceManager.GetString("Permission_Grant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 权限不足。.
        /// </summary>
        public static string Permission_Insufficient {
            get {
                return ResourceManager.GetString("Permission_Insufficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 读取.
        /// </summary>
        public static string Permission_Read {
            get {
                return ResourceManager.GetString("Permission_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请求权限.
        /// </summary>
        public static string Permission_Request {
            get {
                return ResourceManager.GetString("Permission_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 撤销.
        /// </summary>
        public static string Permission_Revoke {
            get {
                return ResourceManager.GetString("Permission_Revoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 权限.
        /// </summary>
        public static string Permission_Title {
            get {
                return ResourceManager.GetString("Permission_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未授权。.
        /// </summary>
        public static string Permission_Unauthorized {
            get {
                return ResourceManager.GetString("Permission_Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 写入.
        /// </summary>
        public static string Permission_Write {
            get {
                return ResourceManager.GetString("Permission_Write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已取消.
        /// </summary>
        public static string Status_Canceled {
            get {
                return ResourceManager.GetString("Status_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已完成.
        /// </summary>
        public static string Status_Completed {
            get {
                return ResourceManager.GetString("Status_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已连接.
        /// </summary>
        public static string Status_Connected {
            get {
                return ResourceManager.GetString("Status_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在连接....
        /// </summary>
        public static string Status_Connecting {
            get {
                return ResourceManager.GetString("Status_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未连接.
        /// </summary>
        public static string Status_Disconnected {
            get {
                return ResourceManager.GetString("Status_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在断开....
        /// </summary>
        public static string Status_Disconnecting {
            get {
                return ResourceManager.GetString("Status_Disconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 空.
        /// </summary>
        public static string Status_Empty {
            get {
                return ResourceManager.GetString("Status_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 失败.
        /// </summary>
        public static string Status_Failed {
            get {
                return ResourceManager.GetString("Status_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 共 {0} 项.
        /// </summary>
        public static string Status_ItemsCountFormat {
            get {
                return ResourceManager.GetString("Status_ItemsCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在加载....
        /// </summary>
        public static string Status_Loading {
            get {
                return ResourceManager.GetString("Status_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暂无数据.
        /// </summary>
        public static string Status_NoData {
            get {
                return ResourceManager.GetString("Status_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已暂停.
        /// </summary>
        public static string Status_Paused {
            get {
                return ResourceManager.GetString("Status_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 就绪.
        /// </summary>
        public static string Status_Ready {
            get {
                return ResourceManager.GetString("Status_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在刷新....
        /// </summary>
        public static string Status_Refreshing {
            get {
                return ResourceManager.GetString("Status_Refreshing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在保存....
        /// </summary>
        public static string Status_Saving {
            get {
                return ResourceManager.GetString("Status_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已选择 {0} 项.
        /// </summary>
        public static string Status_SelectedCountFormat {
            get {
                return ResourceManager.GetString("Status_SelectedCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已停止.
        /// </summary>
        public static string Status_Stopped {
            get {
                return ResourceManager.GetString("Status_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功.
        /// </summary>
        public static string Status_Success {
            get {
                return ResourceManager.GetString("Status_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 处理中....
        /// </summary>
        public static string Status_Working {
            get {
                return ResourceManager.GetString("Status_Working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 强调色.
        /// </summary>
        public static string Theme_AccentColor {
            get {
                return ResourceManager.GetString("Theme_AccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应用主题.
        /// </summary>
        public static string Theme_Apply {
            get {
                return ResourceManager.GetString("Theme_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动.
        /// </summary>
        public static string Theme_Auto {
            get {
                return ResourceManager.GetString("Theme_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 背景.
        /// </summary>
        public static string Theme_Background {
            get {
                return ResourceManager.GetString("Theme_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 圆角.
        /// </summary>
        public static string Theme_CornerRadius {
            get {
                return ResourceManager.GetString("Theme_CornerRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深色.
        /// </summary>
        public static string Theme_Dark {
            get {
                return ResourceManager.GetString("Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字体.
        /// </summary>
        public static string Theme_Font {
            get {
                return ResourceManager.GetString("Theme_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字体大小.
        /// </summary>
        public static string Theme_FontSize {
            get {
                return ResourceManager.GetString("Theme_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 前景.
        /// </summary>
        public static string Theme_Foreground {
            get {
                return ResourceManager.GetString("Theme_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浅色.
        /// </summary>
        public static string Theme_Light {
            get {
                return ResourceManager.GetString("Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主色.
        /// </summary>
        public static string Theme_PrimaryColor {
            get {
                return ResourceManager.GetString("Theme_PrimaryColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 恢复默认主题.
        /// </summary>
        public static string Theme_Reset {
            get {
                return ResourceManager.GetString("Theme_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 阴影.
        /// </summary>
        public static string Theme_Shadow {
            get {
                return ResourceManager.GetString("Theme_Shadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 跟随系统.
        /// </summary>
        public static string Theme_System {
            get {
                return ResourceManager.GetString("Theme_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主题.
        /// </summary>
        public static string Theme_Title {
            get {
                return ResourceManager.GetString("Theme_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 透明度.
        /// </summary>
        public static string Theme_Transparency {
            get {
                return ResourceManager.GetString("Theme_Transparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入无效。.
        /// </summary>
        public static string Validation_Invalid {
            get {
                return ResourceManager.GetString("Validation_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日期无效。.
        /// </summary>
        public static string Validation_InvalidDate {
            get {
                return ResourceManager.GetString("Validation_InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮箱格式不正确。.
        /// </summary>
        public static string Validation_InvalidEmail {
            get {
                return ResourceManager.GetString("Validation_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 格式不正确。.
        /// </summary>
        public static string Validation_InvalidFormat {
            get {
                return ResourceManager.GetString("Validation_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP 地址不合法。.
        /// </summary>
        public static string Validation_InvalidIpAddress {
            get {
                return ResourceManager.GetString("Validation_InvalidIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 电话号码格式不正确。.
        /// </summary>
        public static string Validation_InvalidPhone {
            get {
                return ResourceManager.GetString("Validation_InvalidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 时间无效。.
        /// </summary>
        public static string Validation_InvalidTime {
            get {
                return ResourceManager.GetString("Validation_InvalidTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL 格式不正确。.
        /// </summary>
        public static string Validation_InvalidUrl {
            get {
                return ResourceManager.GetString("Validation_InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 长度必须在 {0} 到 {1} 之间。.
        /// </summary>
        public static string Validation_LengthRangeFormat {
            get {
                return ResourceManager.GetString("Validation_LengthRangeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 长度不能超过 {0}。.
        /// </summary>
        public static string Validation_MaxLengthFormat {
            get {
                return ResourceManager.GetString("Validation_MaxLengthFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不能大于 {0}。.
        /// </summary>
        public static string Validation_MaxValueFormat {
            get {
                return ResourceManager.GetString("Validation_MaxValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 长度不能少于 {0}。.
        /// </summary>
        public static string Validation_MinLengthFormat {
            get {
                return ResourceManager.GetString("Validation_MinLengthFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不能小于 {0}。.
        /// </summary>
        public static string Validation_MinValueFormat {
            get {
                return ResourceManager.GetString("Validation_MinValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 超出允许范围。.
        /// </summary>
        public static string Validation_OutOfRange {
            get {
                return ResourceManager.GetString("Validation_OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 两次输入的密码不一致。.
        /// </summary>
        public static string Validation_PasswordNotMatch {
            get {
                return ResourceManager.GetString("Validation_PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此项为必填项。.
        /// </summary>
        public static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 必须在 {0} 到 {1} 之间。.
        /// </summary>
        public static string Validation_ValueRangeFormat {
            get {
                return ResourceManager.GetString("Validation_ValueRangeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最大化.
        /// </summary>
        public static string Window_Maximize {
            get {
                return ResourceManager.GetString("Window_Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最小化.
        /// </summary>
        public static string Window_Minimize {
            get {
                return ResourceManager.GetString("Window_Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 还原.
        /// </summary>
        public static string Window_Restore {
            get {
                return ResourceManager.GetString("Window_Restore", resourceCulture);
            }
        }
    }
}
