<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\Extensions\H.Extensions.Common\H.Extensions.Common.csproj" />
    <ProjectReference Include="..\..\Extensions\H.Extensions.Mvvm\H.Extensions.Mvvm.csproj" />
    <ProjectReference Include="..\..\Services\H.Services.Message\H.Services.Message.csproj" />
    <ProjectReference Include="..\..\Styles\H.Style\H.Style.csproj" />
  </ItemGroup>
</Project>
