//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H.Extensions.ApplicationBase.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("H.Extensions.ApplicationBase.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初始化数据异常，请看日志.
        /// </summary>
        public static string Message_LoadException {
            get {
                return ResourceManager.GetString("Message_LoadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在加载.
        /// </summary>
        public static string Message_Loading {
            get {
                return ResourceManager.GetString("Message_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在加载设置.
        /// </summary>
        public static string Message_LoadingSetting {
            get {
                return ResourceManager.GetString("Message_LoadingSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在加载模板.
        /// </summary>
        public static string Message_LoadingTempate {
            get {
                return ResourceManager.GetString("Message_LoadingTempate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在加载用户数据.
        /// </summary>
        public static string Message_LoadingUser {
            get {
                return ResourceManager.GetString("Message_LoadingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在加载用户设置数据.
        /// </summary>
        public static string Message_LoadingUserSetting {
            get {
                return ResourceManager.GetString("Message_LoadingUserSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载完成.
        /// </summary>
        public static string Message_LoadSuccess {
            get {
                return ResourceManager.GetString("Message_LoadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前程序已经运行！.
        /// </summary>
        public static string Message_Singleton {
            get {
                return ResourceManager.GetString("Message_Singleton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主题设置.
        /// </summary>
        public static string Type_ThemeOptions {
            get {
                return ResourceManager.GetString("Type_ThemeOptions", resourceCulture);
            }
        }
    }
}
