//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H.Modules.Identity.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("H.Modules.Identity.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 权限管理.
        /// </summary>
        public static string Type_ShowAuthorityViewCommand {
            get {
                return ResourceManager.GetString("Type_ShowAuthorityViewCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应用此功能进行权限管理.
        /// </summary>
        public static string Type_ShowAuthorityViewCommand_Description {
            get {
                return ResourceManager.GetString("Type_ShowAuthorityViewCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 角色管理.
        /// </summary>
        public static string Type_ShowRoleViewCommand {
            get {
                return ResourceManager.GetString("Type_ShowRoleViewCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应用此功能进行角色管理.
        /// </summary>
        public static string Type_ShowRoleViewCommand_Description {
            get {
                return ResourceManager.GetString("Type_ShowRoleViewCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户管理.
        /// </summary>
        public static string Type_ShowUserViewCommand {
            get {
                return ResourceManager.GetString("Type_ShowUserViewCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应用此功能进行用户管理.
        /// </summary>
        public static string Type_ShowUserViewCommand_Description {
            get {
                return ResourceManager.GetString("Type_ShowUserViewCommand_Description", resourceCulture);
            }
        }
    }
}
