//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H.Modules.Identity.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("H.Modules.Identity.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登陆账号.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 权限编码.
        /// </summary>
        public static string AuthorCode {
            get {
                return ResourceManager.GetString("AuthorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 权限名称.
        /// </summary>
        public static string AuthorName {
            get {
                return ResourceManager.GetString("AuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 权限列表.
        /// </summary>
        public static string Authors {
            get {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昵称.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用/禁用.
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 唯一标识.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮箱.
        /// </summary>
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登陆密码.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登陆账号.
        /// </summary>
        public static string Property_hi_dd_user_Account {
            get {
                return ResourceManager.GetString("Property_hi_dd_user_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昵称.
        /// </summary>
        public static string Property_hi_dd_user_DisplayName {
            get {
                return ResourceManager.GetString("Property_hi_dd_user_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用.
        /// </summary>
        public static string Property_hi_dd_user_Enable {
            get {
                return ResourceManager.GetString("Property_hi_dd_user_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最近登录时间.
        /// </summary>
        public static string Property_hi_dd_user_LastLoginTime {
            get {
                return ResourceManager.GetString("Property_hi_dd_user_LastLoginTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 许可截止时间.
        /// </summary>
        public static string Property_hi_dd_user_LicenseDeadline {
            get {
                return ResourceManager.GetString("Property_hi_dd_user_LicenseDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮箱.
        /// </summary>
        public static string Property_hi_dd_user_Mail {
            get {
                return ResourceManager.GetString("Property_hi_dd_user_Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名称.
        /// </summary>
        public static string Property_hi_dd_user_Name {
            get {
                return ResourceManager.GetString("Property_hi_dd_user_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登陆密码.
        /// </summary>
        public static string Property_hi_dd_user_Password {
            get {
                return ResourceManager.GetString("Property_hi_dd_user_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 角色.
        /// </summary>
        public static string Property_hi_dd_user_Role {
            get {
                return ResourceManager.GetString("Property_hi_dd_user_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 角色.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 角色编码.
        /// </summary>
        public static string RoleCode {
            get {
                return ResourceManager.GetString("RoleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 角色名称.
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 角色列表.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 搜索.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 权限管理.
        /// </summary>
        public static string Type_ShowAuthorityViewCommand {
            get {
                return ResourceManager.GetString("Type_ShowAuthorityViewCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应用此功能进行权限管理.
        /// </summary>
        public static string Type_ShowAuthorityViewCommand_Description {
            get {
                return ResourceManager.GetString("Type_ShowAuthorityViewCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 角色管理.
        /// </summary>
        public static string Type_ShowRoleViewCommand {
            get {
                return ResourceManager.GetString("Type_ShowRoleViewCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应用此功能进行角色管理.
        /// </summary>
        public static string Type_ShowRoleViewCommand_Description {
            get {
                return ResourceManager.GetString("Type_ShowRoleViewCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户管理.
        /// </summary>
        public static string Type_ShowUserViewCommand {
            get {
                return ResourceManager.GetString("Type_ShowUserViewCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应用此功能进行用户管理.
        /// </summary>
        public static string Type_ShowUserViewCommand_Description {
            get {
                return ResourceManager.GetString("Type_ShowUserViewCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名称.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户列表.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
