//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace H.Modules.Project.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("H.Modules.Project.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间 的本地化字符串。
        /// </summary>
        public static string Property_ProjectItem_CreateTime {
            get {
                return ResourceManager.GetString("Property_ProjectItem_CreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否固定 的本地化字符串。
        /// </summary>
        public static string Property_ProjectItem_IsFixed {
            get {
                return ResourceManager.GetString("Property_ProjectItem_IsFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恢复默认 的本地化字符串。
        /// </summary>
        public static string Property_ProjectItem_LoadDefaultCommand {
            get {
                return ResourceManager.GetString("Property_ProjectItem_LoadDefaultCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题 的本地化字符串。
        /// </summary>
        public static string Property_ProjectItem_Title {
            get {
                return ResourceManager.GetString("Property_ProjectItem_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改时间 的本地化字符串。
        /// </summary>
        public static string Property_ProjectItem_UpdateTime {
            get {
                return ResourceManager.GetString("Property_ProjectItem_UpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认文件名称 的本地化字符串。
        /// </summary>
        public static string Property_ProjectOptions_DefaultProjectName {
            get {
                return ResourceManager.GetString("Property_ProjectOptions_DefaultProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扩展名 的本地化字符串。
        /// </summary>
        public static string Property_ProjectOptions_Extenstion {
            get {
                return ResourceManager.GetString("Property_ProjectOptions_Extenstion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存的时机 的本地化字符串。
        /// </summary>
        public static string Property_ProjectOptions_SaveMode {
            get {
                return ResourceManager.GetString("Property_ProjectOptions_SaveMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目配置 的本地化字符串。
        /// </summary>
        public static string Type_ProjectOptions {
            get {
                return ResourceManager.GetString("Type_ProjectOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目配置的信息 的本地化字符串。
        /// </summary>
        public static string Type_ProjectOptions_Description {
            get {
                return ResourceManager.GetString("Type_ProjectOptions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统设置 的本地化字符串。
        /// </summary>
        public static string Type_ProjectOptions_GroupName {
            get {
                return ResourceManager.GetString("Type_ProjectOptions_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开项目文件 的本地化字符串。
        /// </summary>
        public static string Type_ShowCurrentProjectFileCommand {
            get {
                return ResourceManager.GetString("Type_ShowCurrentProjectFileCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用记事本打开当前项目的配置文件数据 的本地化字符串。
        /// </summary>
        public static string Type_ShowCurrentProjectFileCommand_Description {
            get {
                return ResourceManager.GetString("Type_ShowCurrentProjectFileCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑项目 的本地化字符串。
        /// </summary>
        public static string Type_ShowEditProjectCommand {
            get {
                return ResourceManager.GetString("Type_ShowEditProjectCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示选中项目编辑页面 的本地化字符串。
        /// </summary>
        public static string Type_ShowEditProjectCommand_Description {
            get {
                return ResourceManager.GetString("Type_ShowEditProjectCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建项目 的本地化字符串。
        /// </summary>
        public static string Type_ShowNewProjectCommand {
            get {
                return ResourceManager.GetString("Type_ShowNewProjectCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示新建项目页面 的本地化字符串。
        /// </summary>
        public static string Type_ShowNewProjectCommand_Description {
            get {
                return ResourceManager.GetString("Type_ShowNewProjectCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开项目 的本地化字符串。
        /// </summary>
        public static string Type_ShowProjectsCommand {
            get {
                return ResourceManager.GetString("Type_ShowProjectsCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示项目列表，选择要打开的项目 的本地化字符串。
        /// </summary>
        public static string Type_ShowProjectsCommand_Description {
            get {
                return ResourceManager.GetString("Type_ShowProjectsCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存项目 的本地化字符串。
        /// </summary>
        public static string Type_ShowSaveProjectCommand {
            get {
                return ResourceManager.GetString("Type_ShowSaveProjectCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存当前选中向导到配置文件中 的本地化字符串。
        /// </summary>
        public static string Type_ShowSaveProjectCommand_Description {
            get {
                return ResourceManager.GetString("Type_ShowSaveProjectCommand_Description", resourceCulture);
            }
        }
    }
}
