//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H.Themes.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("H.Themes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 画刷.
        /// </summary>
        public static string DrawingBrushResource {
            get {
                return ResourceManager.GetString("DrawingBrushResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深色.
        /// </summary>
        public static string Enum_ColorThemeType_Dark {
            get {
                return ResourceManager.GetString("Enum_ColorThemeType_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 常规.
        /// </summary>
        public static string Enum_ColorThemeType_Default {
            get {
                return ResourceManager.GetString("Enum_ColorThemeType_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浅色.
        /// </summary>
        public static string Enum_ColorThemeType_Light {
            get {
                return ResourceManager.GetString("Enum_ColorThemeType_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 常规（推荐）.
        /// </summary>
        public static string Enum_FontSizeThemeType_Default {
            get {
                return ResourceManager.GetString("Enum_FontSizeThemeType_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大.
        /// </summary>
        public static string Enum_FontSizeThemeType_Large {
            get {
                return ResourceManager.GetString("Enum_FontSizeThemeType_Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小.
        /// </summary>
        public static string Enum_FontSizeThemeType_Small {
            get {
                return ResourceManager.GetString("Enum_FontSizeThemeType_Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 常规（推荐）.
        /// </summary>
        public static string Enum_LayoutThemeType_Default {
            get {
                return ResourceManager.GetString("Enum_LayoutThemeType_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 宽松.
        /// </summary>
        public static string Enum_LayoutThemeType_Large {
            get {
                return ResourceManager.GetString("Enum_LayoutThemeType_Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 紧凑.
        /// </summary>
        public static string Enum_LayoutThemeType_Small {
            get {
                return ResourceManager.GetString("Enum_LayoutThemeType_Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片画刷.
        /// </summary>
        public static string ImageBrushResource {
            get {
                return ResourceManager.GetString("ImageBrushResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 渐变（推荐）.
        /// </summary>
        public static string LinearGradientBrushResource {
            get {
                return ResourceManager.GetString("LinearGradientBrushResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中心渐变.
        /// </summary>
        public static string RadialGradientBrushResource {
            get {
                return ResourceManager.GetString("RadialGradientBrushResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纯色（推荐.
        /// </summary>
        public static string SolidColorBrushResource {
            get {
                return ResourceManager.GetString("SolidColorBrushResource", resourceCulture);
            }
        }
    }
}
