//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H.Themes.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("H.Themes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深主题（长期支持）.
        /// </summary>
        public static string AccentDarkColorResource {
            get {
                return ResourceManager.GetString("AccentDarkColorResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纯色.
        /// </summary>
        public static string AccentDarkColorResource_Description {
            get {
                return ResourceManager.GetString("AccentDarkColorResource_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纯色.
        /// </summary>
        public static string AccentDarkColorResource_GroupName {
            get {
                return ResourceManager.GetString("AccentDarkColorResource_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 长期支持.
        /// </summary>
        public static string AccentDarkColorResource_Prompt {
            get {
                return ResourceManager.GetString("AccentDarkColorResource_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浅主题（推荐）.
        /// </summary>
        public static string AccentLightColorResource {
            get {
                return ResourceManager.GetString("AccentLightColorResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纯色.
        /// </summary>
        public static string AccentLightColorResource_Description {
            get {
                return ResourceManager.GetString("AccentLightColorResource_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 强力推荐.
        /// </summary>
        public static string AccentLightColorResource_GroupName {
            get {
                return ResourceManager.GetString("AccentLightColorResource_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 强力推荐.
        /// </summary>
        public static string AccentLightColorResource_Prompt {
            get {
                return ResourceManager.GetString("AccentLightColorResource_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 琥珀终端风.
        /// </summary>
        public static string AmberTerminalDarkColorResource {
            get {
                return ResourceManager.GetString("AmberTerminalDarkColorResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纯色.
        /// </summary>
        public static string AmberTerminalDarkColorResource_Description {
            get {
                return ResourceManager.GetString("AmberTerminalDarkColorResource_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深色科技风.
        /// </summary>
        public static string AmberTerminalDarkColorResource_GroupName {
            get {
                return ResourceManager.GetString("AmberTerminalDarkColorResource_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 试验.
        /// </summary>
        public static string AmberTerminalDarkColorResource_Prompt {
            get {
                return ResourceManager.GetString("AmberTerminalDarkColorResource_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ant Design Pro.
        /// </summary>
        public static string AntDesignProColorResource {
            get {
                return ResourceManager.GetString("AntDesignProColorResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纯色.
        /// </summary>
        public static string AntDesignProColorResource_Description {
            get {
                return ResourceManager.GetString("AntDesignProColorResource_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网站前端风.
        /// </summary>
        public static string AntDesignProColorResource_GroupName {
            get {
                return ResourceManager.GetString("AntDesignProColorResource_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 试验.
        /// </summary>
        public static string AntDesignProColorResource_Prompt {
            get {
                return ResourceManager.GetString("AntDesignProColorResource_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apple (IOS).
        /// </summary>
        public static string AppleColorResource {
            get {
                return ResourceManager.GetString("AppleColorResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纯色.
        /// </summary>
        public static string AppleColorResource_Description {
            get {
                return ResourceManager.GetString("AppleColorResource_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统平台.
        /// </summary>
        public static string AppleColorResource_GroupName {
            get {
                return ResourceManager.GetString("AppleColorResource_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 试验.
        /// </summary>
        public static string AppleColorResource_Prompt {
            get {
                return ResourceManager.GetString("AppleColorResource_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深蓝色（长期支持）.
        /// </summary>
        public static string BlueDarkColorResource {
            get {
                return ResourceManager.GetString("BlueDarkColorResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纯色.
        /// </summary>
        public static string BlueDarkColorResource_Description {
            get {
                return ResourceManager.GetString("BlueDarkColorResource_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纯色.
        /// </summary>
        public static string BlueDarkColorResource_GroupName {
            get {
                return ResourceManager.GetString("BlueDarkColorResource_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 长期支持.
        /// </summary>
        public static string BlueDarkColorResource_Prompt {
            get {
                return ResourceManager.GetString("BlueDarkColorResource_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浅蓝色（长期支持）.
        /// </summary>
        public static string BlueLightColorResource {
            get {
                return ResourceManager.GetString("BlueLightColorResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纯色.
        /// </summary>
        public static string BlueLightColorResource_Description {
            get {
                return ResourceManager.GetString("BlueLightColorResource_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纯色.
        /// </summary>
        public static string BlueLightColorResource_GroupName {
            get {
                return ResourceManager.GetString("BlueLightColorResource_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 长期支持.
        /// </summary>
        public static string BlueLightColorResource_Prompt {
            get {
                return ResourceManager.GetString("BlueLightColorResource_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bootstrap.
        /// </summary>
        public static string BootstrapColorResource {
            get {
                return ResourceManager.GetString("BootstrapColorResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纯色.
        /// </summary>
        public static string BootstrapColorResource_Description {
            get {
                return ResourceManager.GetString("BootstrapColorResource_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网站前端风.
        /// </summary>
        public static string BootstrapColorResource_GroupName {
            get {
                return ResourceManager.GetString("BootstrapColorResource_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 试验.
        /// </summary>
        public static string BootstrapColorResource_Prompt {
            get {
                return ResourceManager.GetString("BootstrapColorResource_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chambray Dark.
        /// </summary>
        public static string ChambrayDarkColorResource {
            get {
                return ResourceManager.GetString("ChambrayDarkColorResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纯色.
        /// </summary>
        public static string ChambrayDarkColorResource_Description {
            get {
                return ResourceManager.GetString("ChambrayDarkColorResource_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纯色.
        /// </summary>
        public static string ChambrayDarkColorResource_GroupName {
            get {
                return ResourceManager.GetString("ChambrayDarkColorResource_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 试验.
        /// </summary>
        public static string ChambrayDarkColorResource_Prompt {
            get {
                return ResourceManager.GetString("ChambrayDarkColorResource_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColorUI-GA.
        /// </summary>
        public static string ColorUIGAColorResource {
            get {
                return ResourceManager.GetString("ColorUIGAColorResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纯色.
        /// </summary>
        public static string ColorUIGAColorResource_Description {
            get {
                return ResourceManager.GetString("ColorUIGAColorResource_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网站前端风.
        /// </summary>
        public static string ColorUIGAColorResource_GroupName {
            get {
                return ResourceManager.GetString("ColorUIGAColorResource_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 试验.
        /// </summary>
        public static string ColorUIGAColorResource_Prompt {
            get {
                return ResourceManager.GetString("ColorUIGAColorResource_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深铜色（推荐）.
        /// </summary>
        public static string CopperColorResource {
            get {
                return ResourceManager.GetString("CopperColorResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纯色.
        /// </summary>
        public static string CopperColorResource_Description {
            get {
                return ResourceManager.GetString("CopperColorResource_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 强力推荐.
        /// </summary>
        public static string CopperColorResource_GroupName {
            get {
                return ResourceManager.GetString("CopperColorResource_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 强力推荐.
        /// </summary>
        public static string CopperColorResource_Prompt {
            get {
                return ResourceManager.GetString("CopperColorResource_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 赛博朋克风.
        /// </summary>
        public static string CyberpunkColorResource {
            get {
                return ResourceManager.GetString("CyberpunkColorResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 霓虹对比色 + 深色背景，适合数据看板、科技感应用.
        /// </summary>
        public static string CyberpunkColorResource_Description {
            get {
                return ResourceManager.GetString("CyberpunkColorResource_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深色科技风.
        /// </summary>
        public static string CyberpunkColorResource_GroupName {
            get {
                return ResourceManager.GetString("CyberpunkColorResource_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 试验.
        /// </summary>
        public static string CyberpunkColorResource_Prompt {
            get {
                return ResourceManager.GetString("CyberpunkColorResource_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深色（推荐）.
        /// </summary>
        public static string DarkColorResource {
            get {
                return ResourceManager.GetString("DarkColorResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纯色.
        /// </summary>
        public static string DarkColorResource_Description {
            get {
                return ResourceManager.GetString("DarkColorResource_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 强力推荐.
        /// </summary>
        public static string DarkColorResource_GroupName {
            get {
                return ResourceManager.GetString("DarkColorResource_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 强力推荐.
        /// </summary>
        public static string DarkColorResource_Prompt {
            get {
                return ResourceManager.GetString("DarkColorResource_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统（长期支持）.
        /// </summary>
        public static string DefaultColorResource {
            get {
                return ResourceManager.GetString("DefaultColorResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纯色.
        /// </summary>
        public static string DefaultColorResource_Description {
            get {
                return ResourceManager.GetString("DefaultColorResource_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纯色.
        /// </summary>
        public static string DefaultColorResource_GroupName {
            get {
                return ResourceManager.GetString("DefaultColorResource_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 长期支持.
        /// </summary>
        public static string DefaultColorResource_Prompt {
            get {
                return ResourceManager.GetString("DefaultColorResource_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 画刷.
        /// </summary>
        public static string DrawingBrushResource {
            get {
                return ResourceManager.GetString("DrawingBrushResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深色.
        /// </summary>
        public static string Enum_ColorThemeType_Dark {
            get {
                return ResourceManager.GetString("Enum_ColorThemeType_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 常规.
        /// </summary>
        public static string Enum_ColorThemeType_Default {
            get {
                return ResourceManager.GetString("Enum_ColorThemeType_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浅色.
        /// </summary>
        public static string Enum_ColorThemeType_Light {
            get {
                return ResourceManager.GetString("Enum_ColorThemeType_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 常规（推荐）.
        /// </summary>
        public static string Enum_FontSizeThemeType_Default {
            get {
                return ResourceManager.GetString("Enum_FontSizeThemeType_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大.
        /// </summary>
        public static string Enum_FontSizeThemeType_Large {
            get {
                return ResourceManager.GetString("Enum_FontSizeThemeType_Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大.
        /// </summary>
        public static string Enum_FontSizeThemeType_Small {
            get {
                return ResourceManager.GetString("Enum_FontSizeThemeType_Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 常规（推荐）.
        /// </summary>
        public static string Enum_LayoutThemeType_Default {
            get {
                return ResourceManager.GetString("Enum_LayoutThemeType_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 宽松.
        /// </summary>
        public static string Enum_LayoutThemeType_Large {
            get {
                return ResourceManager.GetString("Enum_LayoutThemeType_Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 紧凑.
        /// </summary>
        public static string Enum_LayoutThemeType_Small {
            get {
                return ResourceManager.GetString("Enum_LayoutThemeType_Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ‌Fluent UI (Microsoft).
        /// </summary>
        public static string FluentUIColorResource {
            get {
                return ResourceManager.GetString("FluentUIColorResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纯色.
        /// </summary>
        public static string FluentUIColorResource_Description {
            get {
                return ResourceManager.GetString("FluentUIColorResource_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统平台.
        /// </summary>
        public static string FluentUIColorResource_GroupName {
            get {
                return ResourceManager.GetString("FluentUIColorResource_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 试验.
        /// </summary>
        public static string FluentUIColorResource_Prompt {
            get {
                return ResourceManager.GetString("FluentUIColorResource_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未来荧光风.
        /// </summary>
        public static string FuturismColorResource {
            get {
                return ResourceManager.GetString("FuturismColorResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高饱和荧光色 + 深空背景，适合游戏、潮流应用 .
        /// </summary>
        public static string FuturismColorResource_Description {
            get {
                return ResourceManager.GetString("FuturismColorResource_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深色科技风.
        /// </summary>
        public static string FuturismColorResource_GroupName {
            get {
                return ResourceManager.GetString("FuturismColorResource_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 试验.
        /// </summary>
        public static string FuturismColorResource_Prompt {
            get {
                return ResourceManager.GetString("FuturismColorResource_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未来主义绿.
        /// </summary>
        public static string FuturisticGreenDarkColorResource {
            get {
                return ResourceManager.GetString("FuturisticGreenDarkColorResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纯色.
        /// </summary>
        public static string FuturisticGreenDarkColorResource_Description {
            get {
                return ResourceManager.GetString("FuturisticGreenDarkColorResource_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深色科技风.
        /// </summary>
        public static string FuturisticGreenDarkColorResource_GroupName {
            get {
                return ResourceManager.GetString("FuturisticGreenDarkColorResource_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 试验.
        /// </summary>
        public static string FuturisticGreenDarkColorResource_Prompt {
            get {
                return ResourceManager.GetString("FuturisticGreenDarkColorResource_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深灰色（推荐）.
        /// </summary>
        public static string GrayDarkColorResource {
            get {
                return ResourceManager.GetString("GrayDarkColorResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纯色.
        /// </summary>
        public static string GrayDarkColorResource_Description {
            get {
                return ResourceManager.GetString("GrayDarkColorResource_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 强力推荐.
        /// </summary>
        public static string GrayDarkColorResource_GroupName {
            get {
                return ResourceManager.GetString("GrayDarkColorResource_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 强力推荐.
        /// </summary>
        public static string GrayDarkColorResource_Prompt {
            get {
                return ResourceManager.GetString("GrayDarkColorResource_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浅灰色（推荐）.
        /// </summary>
        public static string GrayLightColorResource {
            get {
                return ResourceManager.GetString("GrayLightColorResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纯色.
        /// </summary>
        public static string GrayLightColorResource_Description {
            get {
                return ResourceManager.GetString("GrayLightColorResource_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 强力推荐.
        /// </summary>
        public static string GrayLightColorResource_GroupName {
            get {
                return ResourceManager.GetString("GrayLightColorResource_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 强力推荐.
        /// </summary>
        public static string GrayLightColorResource_Prompt {
            get {
                return ResourceManager.GetString("GrayLightColorResource_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片画刷.
        /// </summary>
        public static string ImageBrushResource {
            get {
                return ResourceManager.GetString("ImageBrushResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暗黑工业风.
        /// </summary>
        public static string IndustrialDarkColorResource {
            get {
                return ResourceManager.GetString("IndustrialDarkColorResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纯色.
        /// </summary>
        public static string IndustrialDarkColorResource_Description {
            get {
                return ResourceManager.GetString("IndustrialDarkColorResource_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生产工业风.
        /// </summary>
        public static string IndustrialDarkColorResource_GroupName {
            get {
                return ResourceManager.GetString("IndustrialDarkColorResource_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 试验.
        /// </summary>
        public static string IndustrialDarkColorResource_Prompt {
            get {
                return ResourceManager.GetString("IndustrialDarkColorResource_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LayUI.
        /// </summary>
        public static string LayUIColorResource {
            get {
                return ResourceManager.GetString("LayUIColorResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纯色.
        /// </summary>
        public static string LayUIColorResource_Description {
            get {
                return ResourceManager.GetString("LayUIColorResource_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网站前端风.
        /// </summary>
        public static string LayUIColorResource_GroupName {
            get {
                return ResourceManager.GetString("LayUIColorResource_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 试验.
        /// </summary>
        public static string LayUIColorResource_Prompt {
            get {
                return ResourceManager.GetString("LayUIColorResource_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浅色（推荐）.
        /// </summary>
        public static string LightColorResource {
            get {
                return ResourceManager.GetString("LightColorResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纯色.
        /// </summary>
        public static string LightColorResource_Description {
            get {
                return ResourceManager.GetString("LightColorResource_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 强力推荐.
        /// </summary>
        public static string LightColorResource_GroupName {
            get {
                return ResourceManager.GetString("LightColorResource_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 强力推荐.
        /// </summary>
        public static string LightColorResource_Prompt {
            get {
                return ResourceManager.GetString("LightColorResource_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 渐变（推荐）.
        /// </summary>
        public static string LinearGradientBrushResource {
            get {
                return ResourceManager.GetString("LinearGradientBrushResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Design 3 (Google).
        /// </summary>
        public static string MaterialDesignColorResource {
            get {
                return ResourceManager.GetString("MaterialDesignColorResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纯色.
        /// </summary>
        public static string MaterialDesignColorResource_Description {
            get {
                return ResourceManager.GetString("MaterialDesignColorResource_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统平台.
        /// </summary>
        public static string MaterialDesignColorResource_GroupName {
            get {
                return ResourceManager.GetString("MaterialDesignColorResource_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 试验.
        /// </summary>
        public static string MaterialDesignColorResource_Prompt {
            get {
                return ResourceManager.GetString("MaterialDesignColorResource_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自然矿物风（长期支持）.
        /// </summary>
        public static string MineralColorResource {
            get {
                return ResourceManager.GetString("MineralColorResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 低饱和度大地色系，柔和自然，适合环保、健康类应用.
        /// </summary>
        public static string MineralColorResource_Description {
            get {
                return ResourceManager.GetString("MineralColorResource_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 柔和复古风.
        /// </summary>
        public static string MineralColorResource_GroupName {
            get {
                return ResourceManager.GetString("MineralColorResource_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 长期支持.
        /// </summary>
        public static string MineralColorResource_Prompt {
            get {
                return ResourceManager.GetString("MineralColorResource_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oracle Dark.
        /// </summary>
        public static string OracleDarkColorResource {
            get {
                return ResourceManager.GetString("OracleDarkColorResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纯色.
        /// </summary>
        public static string OracleDarkColorResource_Description {
            get {
                return ResourceManager.GetString("OracleDarkColorResource_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纯色.
        /// </summary>
        public static string OracleDarkColorResource_GroupName {
            get {
                return ResourceManager.GetString("OracleDarkColorResource_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 试验.
        /// </summary>
        public static string OracleDarkColorResource_Prompt {
            get {
                return ResourceManager.GetString("OracleDarkColorResource_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深紫色（长期支持）.
        /// </summary>
        public static string PurpleDarkColorResource {
            get {
                return ResourceManager.GetString("PurpleDarkColorResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纯色.
        /// </summary>
        public static string PurpleDarkColorResource_Description {
            get {
                return ResourceManager.GetString("PurpleDarkColorResource_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纯色.
        /// </summary>
        public static string PurpleDarkColorResource_GroupName {
            get {
                return ResourceManager.GetString("PurpleDarkColorResource_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 长期支持.
        /// </summary>
        public static string PurpleDarkColorResource_Prompt {
            get {
                return ResourceManager.GetString("PurpleDarkColorResource_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浅紫色（长期支持）.
        /// </summary>
        public static string PurpleLightColorResource {
            get {
                return ResourceManager.GetString("PurpleLightColorResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纯色.
        /// </summary>
        public static string PurpleLightColorResource_Description {
            get {
                return ResourceManager.GetString("PurpleLightColorResource_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纯色.
        /// </summary>
        public static string PurpleLightColorResource_GroupName {
            get {
                return ResourceManager.GetString("PurpleLightColorResource_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 长期支持.
        /// </summary>
        public static string PurpleLightColorResource_Prompt {
            get {
                return ResourceManager.GetString("PurpleLightColorResource_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中心渐变.
        /// </summary>
        public static string RadialGradientBrushResource {
            get {
                return ResourceManager.GetString("RadialGradientBrushResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纯色（推荐.
        /// </summary>
        public static string SolidColorBrushResource {
            get {
                return ResourceManager.GetString("SolidColorBrushResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深空科技蓝（推荐）.
        /// </summary>
        public static string TechnologyBlueDarkColorResource {
            get {
                return ResourceManager.GetString("TechnologyBlueDarkColorResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纯色.
        /// </summary>
        public static string TechnologyBlueDarkColorResource_Description {
            get {
                return ResourceManager.GetString("TechnologyBlueDarkColorResource_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 强力推荐.
        /// </summary>
        public static string TechnologyBlueDarkColorResource_GroupName {
            get {
                return ResourceManager.GetString("TechnologyBlueDarkColorResource_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 强力推荐.
        /// </summary>
        public static string TechnologyBlueDarkColorResource_Prompt {
            get {
                return ResourceManager.GetString("TechnologyBlueDarkColorResource_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 电骼兽藏青.
        /// </summary>
        public static string TechnologyCyanColorResource {
            get {
                return ResourceManager.GetString("TechnologyCyanColorResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深邃而神秘，如同夜晚的星空，引人深思.
        /// </summary>
        public static string TechnologyCyanColorResource_Description {
            get {
                return ResourceManager.GetString("TechnologyCyanColorResource_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深色科技风.
        /// </summary>
        public static string TechnologyCyanColorResource_GroupName {
            get {
                return ResourceManager.GetString("TechnologyCyanColorResource_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 试验.
        /// </summary>
        public static string TechnologyCyanColorResource_Prompt {
            get {
                return ResourceManager.GetString("TechnologyCyanColorResource_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 星际无线靛.
        /// </summary>
        public static string TechnologyIndigoColorResource {
            get {
                return ResourceManager.GetString("TechnologyIndigoColorResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深邃而广阔，如同无垠的宇宙，充满了未知与探索.
        /// </summary>
        public static string TechnologyIndigoColorResource_Description {
            get {
                return ResourceManager.GetString("TechnologyIndigoColorResource_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深色科技风.
        /// </summary>
        public static string TechnologyIndigoColorResource_GroupName {
            get {
                return ResourceManager.GetString("TechnologyIndigoColorResource_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 试验.
        /// </summary>
        public static string TechnologyIndigoColorResource_Prompt {
            get {
                return ResourceManager.GetString("TechnologyIndigoColorResource_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 芭比曙光粉（长期支持）.
        /// </summary>
        public static string TechnologyPinkColorResource {
            get {
                return ResourceManager.GetString("TechnologyPinkColorResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 明亮而充满活力，如同晨曦中的第一缕阳光，温暖而希望.
        /// </summary>
        public static string TechnologyPinkColorResource_Description {
            get {
                return ResourceManager.GetString("TechnologyPinkColorResource_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清新自然风.
        /// </summary>
        public static string TechnologyPinkColorResource_GroupName {
            get {
                return ResourceManager.GetString("TechnologyPinkColorResource_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 长期支持.
        /// </summary>
        public static string TechnologyPinkColorResource_Prompt {
            get {
                return ResourceManager.GetString("TechnologyPinkColorResource_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深空科技紫.
        /// </summary>
        public static string TechnologyPurpleColorResource {
            get {
                return ResourceManager.GetString("TechnologyPurpleColorResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纯色.
        /// </summary>
        public static string TechnologyPurpleColorResource_Description {
            get {
                return ResourceManager.GetString("TechnologyPurpleColorResource_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深色科技风.
        /// </summary>
        public static string TechnologyPurpleColorResource_GroupName {
            get {
                return ResourceManager.GetString("TechnologyPurpleColorResource_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 试验.
        /// </summary>
        public static string TechnologyPurpleColorResource_Prompt {
            get {
                return ResourceManager.GetString("TechnologyPurpleColorResource_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 春日生机（推荐）.
        /// </summary>
        public static string TechnologySOIORColorResource {
            get {
                return ResourceManager.GetString("TechnologySOIORColorResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清新而自然，如同春天的气息，充满了生机与活力.
        /// </summary>
        public static string TechnologySOIORColorResource_Description {
            get {
                return ResourceManager.GetString("TechnologySOIORColorResource_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 强力推荐.
        /// </summary>
        public static string TechnologySOIORColorResource_GroupName {
            get {
                return ResourceManager.GetString("TechnologySOIORColorResource_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 强力推荐.
        /// </summary>
        public static string TechnologySOIORColorResource_Prompt {
            get {
                return ResourceManager.GetString("TechnologySOIORColorResource_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viking Dark.
        /// </summary>
        public static string VikingDarkColorResource {
            get {
                return ResourceManager.GetString("VikingDarkColorResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纯色.
        /// </summary>
        public static string VikingDarkColorResource_Description {
            get {
                return ResourceManager.GetString("VikingDarkColorResource_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纯色.
        /// </summary>
        public static string VikingDarkColorResource_GroupName {
            get {
                return ResourceManager.GetString("VikingDarkColorResource_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 试验.
        /// </summary>
        public static string VikingDarkColorResource_Prompt {
            get {
                return ResourceManager.GetString("VikingDarkColorResource_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复古胶片风（推荐）.
        /// </summary>
        public static string VintageFilmColorResource {
            get {
                return ResourceManager.GetString("VintageFilmColorResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暖调褪色感，适合摄影、文艺类应用.
        /// </summary>
        public static string VintageFilmColorResource_Description {
            get {
                return ResourceManager.GetString("VintageFilmColorResource_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 柔和复古风.
        /// </summary>
        public static string VintageFilmColorResource_GroupName {
            get {
                return ResourceManager.GetString("VintageFilmColorResource_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 强力推荐.
        /// </summary>
        public static string VintageFilmColorResource_Prompt {
            get {
                return ResourceManager.GetString("VintageFilmColorResource_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网站前端风（推荐）.
        /// </summary>
        public static string WebLightUIColorResource {
            get {
                return ResourceManager.GetString("WebLightUIColorResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纯色.
        /// </summary>
        public static string WebLightUIColorResource_Description {
            get {
                return ResourceManager.GetString("WebLightUIColorResource_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 强力推荐.
        /// </summary>
        public static string WebLightUIColorResource_GroupName {
            get {
                return ResourceManager.GetString("WebLightUIColorResource_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 强力推荐.
        /// </summary>
        public static string WebLightUIColorResource_Prompt {
            get {
                return ResourceManager.GetString("WebLightUIColorResource_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeUI.
        /// </summary>
        public static string WeUIColorResource {
            get {
                return ResourceManager.GetString("WeUIColorResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纯色.
        /// </summary>
        public static string WeUIColorResource_Description {
            get {
                return ResourceManager.GetString("WeUIColorResource_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网站前端风.
        /// </summary>
        public static string WeUIColorResource_GroupName {
            get {
                return ResourceManager.GetString("WeUIColorResource_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 试验.
        /// </summary>
        public static string WeUIColorResource_Prompt {
            get {
                return ResourceManager.GetString("WeUIColorResource_Prompt", resourceCulture);
            }
        }
    }
}
