//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace H.Themes.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("H.Themes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 画刷 的本地化字符串。
        /// </summary>
        public static string DrawingBrushResource {
            get {
                return ResourceManager.GetString("DrawingBrushResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 深色 的本地化字符串。
        /// </summary>
        public static string Enum_ColorThemeType_Dark {
            get {
                return ResourceManager.GetString("Enum_ColorThemeType_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常规 的本地化字符串。
        /// </summary>
        public static string Enum_ColorThemeType_Default {
            get {
                return ResourceManager.GetString("Enum_ColorThemeType_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浅色 的本地化字符串。
        /// </summary>
        public static string Enum_ColorThemeType_Light {
            get {
                return ResourceManager.GetString("Enum_ColorThemeType_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常规（推荐） 的本地化字符串。
        /// </summary>
        public static string Enum_FontSizeThemeType_Default {
            get {
                return ResourceManager.GetString("Enum_FontSizeThemeType_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大 的本地化字符串。
        /// </summary>
        public static string Enum_FontSizeThemeType_Large {
            get {
                return ResourceManager.GetString("Enum_FontSizeThemeType_Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大 的本地化字符串。
        /// </summary>
        public static string Enum_FontSizeThemeType_Small {
            get {
                return ResourceManager.GetString("Enum_FontSizeThemeType_Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常规（推荐） 的本地化字符串。
        /// </summary>
        public static string Enum_LayoutThemeType_Default {
            get {
                return ResourceManager.GetString("Enum_LayoutThemeType_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宽松 的本地化字符串。
        /// </summary>
        public static string Enum_LayoutThemeType_Large {
            get {
                return ResourceManager.GetString("Enum_LayoutThemeType_Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 紧凑 的本地化字符串。
        /// </summary>
        public static string Enum_LayoutThemeType_Small {
            get {
                return ResourceManager.GetString("Enum_LayoutThemeType_Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片画刷 的本地化字符串。
        /// </summary>
        public static string ImageBrushResource {
            get {
                return ResourceManager.GetString("ImageBrushResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 渐变（推荐） 的本地化字符串。
        /// </summary>
        public static string LinearGradientBrushResource {
            get {
                return ResourceManager.GetString("LinearGradientBrushResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中心渐变 的本地化字符串。
        /// </summary>
        public static string RadialGradientBrushResource {
            get {
                return ResourceManager.GetString("RadialGradientBrushResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纯色（推荐 的本地化字符串。
        /// </summary>
        public static string SolidColorBrushResource {
            get {
                return ResourceManager.GetString("SolidColorBrushResource", resourceCulture);
            }
        }
    }
}
