//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H.Modules.Theme.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("H.Modules.Theme.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 默认按钮.
        /// </summary>
        public static string DefaultButton {
            get {
                return ResourceManager.GetString("DefaultButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 背景配色.
        /// </summary>
        public static string Property_ThemeOptions_BackgroundResource {
            get {
                return ResourceManager.GetString("Property_ThemeOptions_BackgroundResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配色.
        /// </summary>
        public static string Property_ThemeOptions_ColorResource {
            get {
                return ResourceManager.GetString("Property_ThemeOptions_ColorResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字体.
        /// </summary>
        public static string Property_ThemeOptions_FontFamily {
            get {
                return ResourceManager.GetString("Property_ThemeOptions_FontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字号.
        /// </summary>
        public static string Property_ThemeOptions_FontSize {
            get {
                return ResourceManager.GetString("Property_ThemeOptions_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图标字体.
        /// </summary>
        public static string Property_ThemeOptions_IconFontFamily {
            get {
                return ResourceManager.GetString("Property_ThemeOptions_IconFontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 切换明暗主题.
        /// </summary>
        public static string Property_ThemeOptions_IsDark {
            get {
                return ResourceManager.GetString("Property_ThemeOptions_IsDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 布局.
        /// </summary>
        public static string Property_ThemeOptions_Layout {
            get {
                return ResourceManager.GetString("Property_ThemeOptions_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 切换明暗主题.
        /// </summary>
        public static string SwitchTheme {
            get {
                return ResourceManager.GetString("SwitchTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 颜色主题.
        /// </summary>
        public static string Type_ShowColorThemeViewCommand {
            get {
                return ResourceManager.GetString("Type_ShowColorThemeViewCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示设置颜色主题.
        /// </summary>
        public static string Type_ShowColorThemeViewCommand_Description {
            get {
                return ResourceManager.GetString("Type_ShowColorThemeViewCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主题设置.
        /// </summary>
        public static string Type_ThemeOptions {
            get {
                return ResourceManager.GetString("Type_ThemeOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主题设置设置的信息.
        /// </summary>
        public static string Type_ThemeOptions_Description {
            get {
                return ResourceManager.GetString("Type_ThemeOptions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示设置.
        /// </summary>
        public static string Type_ThemeOptions_GroupName {
            get {
                return ResourceManager.GetString("Type_ThemeOptions_GroupName", resourceCulture);
            }
        }
    }
}
