//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H.Modules.Login.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("H.Modules.Login.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账号.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账号登录.
        /// </summary>
        public static string AccountLogin {
            get {
                return ResourceManager.GetString("AccountLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我已阅读并同意.
        /// </summary>
        public static string Agree {
            get {
                return ResourceManager.GetString("Agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 和.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改密码.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认密码.
        /// </summary>
        public static string ConfirmationPassword {
            get {
                return ResourceManager.GetString("ConfirmationPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮箱地址.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮箱验证.
        /// </summary>
        public static string EmailVerification {
            get {
                return ResourceManager.GetString("EmailVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 忘记密码.
        /// </summary>
        public static string ForgetPassword {
            get {
                return ResourceManager.GetString("ForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在{0}....
        /// </summary>
        public static string Format_Doing {
            get {
                return ResourceManager.GetString("Format_Doing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}成功.
        /// </summary>
        public static string Format_Success {
            get {
                return ResourceManager.GetString("Format_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取验证码.
        /// </summary>
        public static string GetVerificationCode {
            get {
                return ResourceManager.GetString("GetVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入用户名.
        /// </summary>
        public static string InputAccount {
            get {
                return ResourceManager.GetString("InputAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入密码.
        /// </summary>
        public static string InputPassword {
            get {
                return ResourceManager.GetString("InputPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 执行中....
        /// </summary>
        public static string Invoking {
            get {
                return ResourceManager.GetString("Invoking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 直接登录.
        /// </summary>
        public static string LoginDirect {
            get {
                return ResourceManager.GetString("LoginDirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下一步.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上一步.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 隐私政策.
        /// </summary>
        public static string Privacypolicy {
            get {
                return ResourceManager.GetString("Privacypolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理员账号.
        /// </summary>
        public static string Property_LoginOptions_AdminName {
            get {
                return ResourceManager.GetString("Property_LoginOptions_AdminName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上次登录用户.
        /// </summary>
        public static string Property_LoginOptions_LastUserName {
            get {
                return ResourceManager.GetString("Property_LoginOptions_LastUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录标题.
        /// </summary>
        public static string Property_LoginOptions_Product {
            get {
                return ResourceManager.GetString("Property_LoginOptions_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字体大小.
        /// </summary>
        public static string Property_LoginOptions_ProductFontSize {
            get {
                return ResourceManager.GetString("Property_LoginOptions_ProductFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 记住密码.
        /// </summary>
        public static string Property_LoginOptions_Remember {
            get {
                return ResourceManager.GetString("Property_LoginOptions_Remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出登录重启.
        /// </summary>
        public static string Property_LoginOptions_UseLogoutRestart {
            get {
                return ResourceManager.GetString("Property_LoginOptions_UseLogoutRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用退出登录重启应用.
        /// </summary>
        public static string Property_LoginOptions_UseLogoutRestart_Description {
            get {
                return ResourceManager.GetString("Property_LoginOptions_UseLogoutRestart_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用访客.
        /// </summary>
        public static string Property_LoginOptions_UseVisitor {
            get {
                return ResourceManager.GetString("Property_LoginOptions_UseVisitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用访客模式后登录不成功也可以进入主窗口.
        /// </summary>
        public static string Property_LoginOptions_UseVisitor_Description {
            get {
                return ResourceManager.GetString("Property_LoginOptions_UseVisitor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 左侧图片.
        /// </summary>
        public static string Property_RegistorOptions_Image {
            get {
                return ResourceManager.GetString("Property_RegistorOptions_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发送验证码的邮箱.
        /// </summary>
        public static string Property_RegistorOptions_MailAccount {
            get {
                return ResourceManager.GetString("Property_RegistorOptions_MailAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 隐私策略.
        /// </summary>
        public static string Property_RegistorOptions_PrivacypolicyUri {
            get {
                return ResourceManager.GetString("Property_RegistorOptions_PrivacypolicyUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应用许可.
        /// </summary>
        public static string Property_RegistorOptions_ServiceAgreementUri {
            get {
                return ResourceManager.GetString("Property_RegistorOptions_ServiceAgreementUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用邮箱注册.
        /// </summary>
        public static string Property_RegistorOptions_UseMail {
            get {
                return ResourceManager.GetString("Property_RegistorOptions_UseMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用邮箱注册.
        /// </summary>
        public static string Property_RegistorOptions_UseMail_Description {
            get {
                return ResourceManager.GetString("Property_RegistorOptions_UseMail_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册账号.
        /// </summary>
        public static string RegisterAccount {
            get {
                return ResourceManager.GetString("RegisterAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 立即注册.
        /// </summary>
        public static string RegisterNow {
            get {
                return ResourceManager.GetString("RegisterNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册验证码.
        /// </summary>
        public static string RegisterVerificationCode {
            get {
                return ResourceManager.GetString("RegisterVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 记住密码.
        /// </summary>
        public static string RemenberPassword {
            get {
                return ResourceManager.GetString("RemenberPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发送邮件中.
        /// </summary>
        public static string SendingEmail {
            get {
                return ResourceManager.GetString("SendingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服务协议.
        /// </summary>
        public static string ServiceAgreement {
            get {
                return ResourceManager.GetString("ServiceAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录页面设置.
        /// </summary>
        public static string Type_LoginOptions {
            get {
                return ResourceManager.GetString("Type_LoginOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录页面设置的信息.
        /// </summary>
        public static string Type_LoginOptions_Description {
            get {
                return ResourceManager.GetString("Type_LoginOptions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统设置.
        /// </summary>
        public static string Type_LoginOptions_GroupName {
            get {
                return ResourceManager.GetString("Type_LoginOptions_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册页面设置.
        /// </summary>
        public static string Type_RegistorOptions {
            get {
                return ResourceManager.GetString("Type_RegistorOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册页面设置的信息.
        /// </summary>
        public static string Type_RegistorOptions_Description {
            get {
                return ResourceManager.GetString("Type_RegistorOptions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统设置.
        /// </summary>
        public static string Type_RegistorOptions_GroupName {
            get {
                return ResourceManager.GetString("Type_RegistorOptions_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户登录.
        /// </summary>
        public static string UserLogin {
            get {
                return ResourceManager.GetString("UserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 验证码.
        /// </summary>
        public static string VerificationCode {
            get {
                return ResourceManager.GetString("VerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 验证码已发送.
        /// </summary>
        public static string VerificationCodeSended {
            get {
                return ResourceManager.GetString("VerificationCodeSended", resourceCulture);
            }
        }
    }
}
