using System;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using System.Reflection;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows;
using Microsoft.Xaml.Behaviors;
using System.Windows.Threading;

namespace H.Extensions.Behvaiors
{
    public class AutoColumnDataGridBehavior : Behavior<DataGrid>
    {
        protected override void OnAttached()
        {
            this.AssociatedObject.AutoGeneratedColumns += AssociatedObject_AutoGeneratedColumns;
        }


        public Type Type
        {
            get { return (Type)GetValue(TypeProperty); }
            set { SetValue(TypeProperty, value); }
        }

        // Using a DependencyProperty as the backing store for MyProperty.  This enables animation, styling, binding, etc...
        public static readonly DependencyProperty TypeProperty =
            DependencyProperty.Register("Type", typeof(Type), typeof(AutoColumnDataGridBehavior), new FrameworkPropertyMetadata(default(Type), (d, e) =>
            {
                AutoColumnDataGridBehavior control = d as AutoColumnDataGridBehavior;

                if (control == null) return;

                if (e.OldValue is Type o)
                {

                }

                if (e.NewValue is Type n)
                {

                }

            }));

        /// <summary>
        /// Model.{0}
        /// </summary>
        public string BindingPath
        {
            get { return (string)GetValue(BindingPathProperty); }
            set { SetValue(BindingPathProperty, value); }
        }

        // Using a DependencyProperty as the backing store for MyProperty.  This enables animation, styling, binding, etc...
        public static readonly DependencyProperty BindingPathProperty =
            DependencyProperty.Register("BindingPath", typeof(string), typeof(AutoColumnDataGridBehavior), new FrameworkPropertyMetadata("{0}", (d, e) =>
            {
                AutoColumnDataGridBehavior control = d as AutoColumnDataGridBehavior;

                if (control == null) return;

                if (e.OldValue is string o)
                {

                }

                if (e.NewValue is string n)
                {

                }

                control.GenerateColumns();
            }));

        public DataGridLength DataGridLength
        {
            get { return (DataGridLength)GetValue(DataGridLengthProperty); }
            set { SetValue(DataGridLengthProperty, value); }
        }

        // Using a DependencyProperty as the backing store for MyProperty.  This enables animation, styling, binding, etc...
        public static readonly DependencyProperty DataGridLengthProperty =
            DependencyProperty.Register("DataGridLength", typeof(DataGridLength), typeof(AutoColumnDataGridBehavior), new FrameworkPropertyMetadata(DataGridLength.Auto, (d, e) =>
            {
                AutoColumnDataGridBehavior control = d as AutoColumnDataGridBehavior;

                if (control == null) return;

                if (e.OldValue is DataGridLength o)
                {

                }

                if (e.NewValue is DataGridLength n)
                {

                }
                control.GenerateColumns();

            }));


        private void AssociatedObject_AutoGeneratedColumns(object sender, EventArgs e)
        {
            this.GenerateColumns();
        }

        protected override void OnDetaching()
        {
            this.AssociatedObject.AutoGeneratedColumns -= AssociatedObject_AutoGeneratedColumns;
        }

        public ObservableCollection<DataGridColumn> HomeColumns { get; } = new ObservableCollection<DataGridColumn>();
        public ObservableCollection<DataGridColumn> EndColumns { get; } = new ObservableCollection<DataGridColumn>();


        void GenerateColumns()
        {
            this.DelayInvoke(() =>
            {
                this.GenerateColunms(this.AssociatedObject);
            });
        }

        protected virtual void GenerateColunms(DataGrid dataGrid)
        {
            if (dataGrid == null)
                return;
            if (dataGrid.IsInitialized == false)
                return;
            dataGrid.Columns.Clear();
            foreach (DataGridColumn item in this.HomeColumns)
            {
                dataGrid.Columns.Add(item);
            }
            if (this.Type == null)
                return;
            PropertyInfo[] ps = this.Type.GetProperties();
            foreach (PropertyInfo p in ps)
            {
                BrowsableAttribute browsable = p.GetCustomAttribute<BrowsableAttribute>();
                if (browsable?.Browsable == false)
                    continue;
                DisplayAttribute display = p.GetCustomAttribute<DisplayAttribute>();
                ReadOnlyAttribute readOnly = p.GetCustomAttribute<ReadOnlyAttribute>();
                DataGridColumnAttribute columnAttribute = p.GetCustomAttribute<DataGridColumnAttribute>();
                DataGridColumn column = columnAttribute == null ? this.GetDataGridColumn(p)
                    : columnAttribute.GetDataGridColumn(p);
                column.Header = display?.Name ?? p.Name;
                if (column is DataGridBoundColumn bound)
                {
                    Binding binding = new Binding();
                    string path = string.Format(this.BindingPath, string.Format(columnAttribute?.PropertyPath ?? "{0}", p.Name));
                    binding.Path = new PropertyPath(path);
                    binding.Mode = readOnly?.IsReadOnly == true ? BindingMode.OneWay : BindingMode.TwoWay;
                    bound.Binding = binding;
                }
                dataGrid.Columns.Add(column);
            }
            foreach (DataGridColumn item in this.EndColumns)
            {
                dataGrid.Columns.Add(item);
            }

        }

        public DataGridColumn GetDataGridColumn(PropertyInfo propertyInfo)
        {
            if (propertyInfo.PropertyType == typeof(bool))
            {
                return new DataGridCheckBoxColumn() { Width = this.DataGridLength };
            }
            else if (propertyInfo.PropertyType.IsEnum)
            {
                return new DataGridComboBoxColumn() { Width = this.DataGridLength };
            }
            else
            {
                return new DataGridTextColumn() { Width = this.DataGridLength };
            }
        }
    }
}
