//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H.Data.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("H.Data.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地址.
        /// </summary>
        public static string Property_Student_Address {
            get {
                return ResourceManager.GetString("Property_Student_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 学生的地址.
        /// </summary>
        public static string Property_Student_Address_Description {
            get {
                return ResourceManager.GetString("Property_Student_Address_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 默认分组.
        /// </summary>
        public static string Property_Student_Address_GroupName {
            get {
                return ResourceManager.GetString("Property_Student_Address_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 年龄.
        /// </summary>
        public static string Property_Student_Age {
            get {
                return ResourceManager.GetString("Property_Student_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 学生的年龄.
        /// </summary>
        public static string Property_Student_Age_Description {
            get {
                return ResourceManager.GetString("Property_Student_Age_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 默认分组.
        /// </summary>
        public static string Property_Student_Age_GroupName {
            get {
                return ResourceManager.GetString("Property_Student_Age_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 班级.
        /// </summary>
        public static string Property_Student_Class {
            get {
                return ResourceManager.GetString("Property_Student_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 学生的班级.
        /// </summary>
        public static string Property_Student_Class_Description {
            get {
                return ResourceManager.GetString("Property_Student_Class_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 默认分组.
        /// </summary>
        public static string Property_Student_Class_GroupName {
            get {
                return ResourceManager.GetString("Property_Student_Class_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮箱.
        /// </summary>
        public static string Property_Student_Emall {
            get {
                return ResourceManager.GetString("Property_Student_Emall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 学生的邮箱.
        /// </summary>
        public static string Property_Student_Emall_Description {
            get {
                return ResourceManager.GetString("Property_Student_Emall_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 默认分组.
        /// </summary>
        public static string Property_Student_Emall_GroupName {
            get {
                return ResourceManager.GetString("Property_Student_Emall_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可用.
        /// </summary>
        public static string Property_Student_IsEnbled {
            get {
                return ResourceManager.GetString("Property_Student_IsEnbled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 学生的可用.
        /// </summary>
        public static string Property_Student_IsEnbled_Description {
            get {
                return ResourceManager.GetString("Property_Student_IsEnbled_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 默认分组.
        /// </summary>
        public static string Property_Student_IsEnbled_GroupName {
            get {
                return ResourceManager.GetString("Property_Student_IsEnbled_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 姓名.
        /// </summary>
        public static string Property_Student_Name {
            get {
                return ResourceManager.GetString("Property_Student_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 学生的姓名.
        /// </summary>
        public static string Property_Student_Name_Description {
            get {
                return ResourceManager.GetString("Property_Student_Name_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 默认分组.
        /// </summary>
        public static string Property_Student_Name_GroupName {
            get {
                return ResourceManager.GetString("Property_Student_Name_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分数.
        /// </summary>
        public static string Property_Student_Score {
            get {
                return ResourceManager.GetString("Property_Student_Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 学生的分数.
        /// </summary>
        public static string Property_Student_Score_Description {
            get {
                return ResourceManager.GetString("Property_Student_Score_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 默认分组.
        /// </summary>
        public static string Property_Student_Score_GroupName {
            get {
                return ResourceManager.GetString("Property_Student_Score_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标签.
        /// </summary>
        public static string Property_Student_Tag {
            get {
                return ResourceManager.GetString("Property_Student_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 学生的标签.
        /// </summary>
        public static string Property_Student_Tag_Description {
            get {
                return ResourceManager.GetString("Property_Student_Tag_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 默认分组.
        /// </summary>
        public static string Property_Student_Tag_GroupName {
            get {
                return ResourceManager.GetString("Property_Student_Tag_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 时间.
        /// </summary>
        public static string Property_Student_Time {
            get {
                return ResourceManager.GetString("Property_Student_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 学生的时间.
        /// </summary>
        public static string Property_Student_Time_Description {
            get {
                return ResourceManager.GetString("Property_Student_Time_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 默认分组.
        /// </summary>
        public static string Property_Student_Time_GroupName {
            get {
                return ResourceManager.GetString("Property_Student_Time_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 学生.
        /// </summary>
        public static string Type_Student {
            get {
                return ResourceManager.GetString("Type_Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 学生.
        /// </summary>
        public static string Type_Student_Description {
            get {
                return ResourceManager.GetString("Type_Student_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 学生.
        /// </summary>
        public static string Type_Student1 {
            get {
                return ResourceManager.GetString("Type_Student1", resourceCulture);
            }
        }
    }
}
