//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H.Windows.Main.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("H.Windows.Main.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 窗口背景图片.
        /// </summary>
        public static string Property_WindowSetting_BackImagePath {
            get {
                return ResourceManager.GetString("Property_WindowSetting_BackImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片透明度.
        /// </summary>
        public static string Property_WindowSetting_Opacity {
            get {
                return ResourceManager.GetString("Property_WindowSetting_Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片拉伸.
        /// </summary>
        public static string Property_WindowSetting_Stretch {
            get {
                return ResourceManager.GetString("Property_WindowSetting_Stretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用窗口背景图片.
        /// </summary>
        public static string Property_WindowSetting_UseBackImage {
            get {
                return ResourceManager.GetString("Property_WindowSetting_UseBackImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主窗口关闭提示.
        /// </summary>
        public static string Property_WindowSetting_UseNoticeOnMainWindowClose {
            get {
                return ResourceManager.GetString("Property_WindowSetting_UseNoticeOnMainWindowClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当主窗口点击关闭时会提示是否关闭窗口.
        /// </summary>
        public static string Property_WindowSetting_UseNoticeOnMainWindowClose_Description {
            get {
                return ResourceManager.GetString("Property_WindowSetting_UseNoticeOnMainWindowClose_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主窗口关闭保存数据.
        /// </summary>
        public static string Property_WindowSetting_UseSaveOnMainWindowClose {
            get {
                return ResourceManager.GetString("Property_WindowSetting_UseSaveOnMainWindowClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当主窗口点击关闭时主窗口关闭保存数据.
        /// </summary>
        public static string Property_WindowSetting_UseSaveOnMainWindowClose_Description {
            get {
                return ResourceManager.GetString("Property_WindowSetting_UseSaveOnMainWindowClose_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 窗口设置.
        /// </summary>
        public static string Type_WindowSetting {
            get {
                return ResourceManager.GetString("Type_WindowSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置窗口参数.
        /// </summary>
        public static string Type_WindowSetting_Description {
            get {
                return ResourceManager.GetString("Type_WindowSetting_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 控件设置.
        /// </summary>
        public static string Type_WindowSetting_GroupName {
            get {
                return ResourceManager.GetString("Type_WindowSetting_GroupName", resourceCulture);
            }
        }
    }
}
