//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H.Modules.Help.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("H.Modules.Help.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 博客地址.
        /// </summary>
        public static string Property_ContactOptions_Blog {
            get {
                return ResourceManager.GetString("Property_ContactOptions_Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发送邮箱.
        /// </summary>
        public static string Property_ContactOptions_Email {
            get {
                return ResourceManager.GetString("Property_ContactOptions_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub地址.
        /// </summary>
        public static string Property_ContactOptions_GitHub {
            get {
                return ResourceManager.GetString("Property_ContactOptions_GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提出问题.
        /// </summary>
        public static string Property_ContactOptions_GitHubIssue {
            get {
                return ResourceManager.GetString("Property_ContactOptions_GitHubIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 播客地址.
        /// </summary>
        public static string Property_ContactOptions_Podcast {
            get {
                return ResourceManager.GetString("Property_ContactOptions_Podcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加QQ.
        /// </summary>
        public static string Property_ContactOptions_QQ {
            get {
                return ResourceManager.GetString("Property_ContactOptions_QQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地址.
        /// </summary>
        public static string Property_ReleaseVersionsOptions_Uri {
            get {
                return ResourceManager.GetString("Property_ReleaseVersionsOptions_Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地址.
        /// </summary>
        public static string Property_SupportOptions_Uri {
            get {
                return ResourceManager.GetString("Property_SupportOptions_Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地址.
        /// </summary>
        public static string Property_WebsiteOptions_Uri {
            get {
                return ResourceManager.GetString("Property_WebsiteOptions_Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 联系方式.
        /// </summary>
        public static string Type_ContactOptions {
            get {
                return ResourceManager.GetString("Type_ContactOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通过此方式可以联系到开发者.
        /// </summary>
        public static string Type_ContactOptions_Description {
            get {
                return ResourceManager.GetString("Type_ContactOptions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统设置.
        /// </summary>
        public static string Type_ContactOptions_GroupName {
            get {
                return ResourceManager.GetString("Type_ContactOptions_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发行说明.
        /// </summary>
        public static string Type_ReleaseVersionsOptions {
            get {
                return ResourceManager.GetString("Type_ReleaseVersionsOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看软件发行说明.
        /// </summary>
        public static string Type_ReleaseVersionsOptions_Description {
            get {
                return ResourceManager.GetString("Type_ReleaseVersionsOptions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统设置.
        /// </summary>
        public static string Type_ReleaseVersionsOptions_GroupName {
            get {
                return ResourceManager.GetString("Type_ReleaseVersionsOptions_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 访问博客.
        /// </summary>
        public static string Type_ShowBlogContactCommand {
            get {
                return ResourceManager.GetString("Type_ShowBlogContactCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通过此方式联系到开发者.
        /// </summary>
        public static string Type_ShowBlogContactCommand_Description {
            get {
                return ResourceManager.GetString("Type_ShowBlogContactCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 联系方式.
        /// </summary>
        public static string Type_ShowContactCommand {
            get {
                return ResourceManager.GetString("Type_ShowContactCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通过此方式联系到开发者.
        /// </summary>
        public static string Type_ShowContactCommand_Description {
            get {
                return ResourceManager.GetString("Type_ShowContactCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 访问Github.
        /// </summary>
        public static string Type_ShowGithubContactCommand {
            get {
                return ResourceManager.GetString("Type_ShowGithubContactCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通过此方式联系到开发者.
        /// </summary>
        public static string Type_ShowGithubContactCommand_Description {
            get {
                return ResourceManager.GetString("Type_ShowGithubContactCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提出问题.
        /// </summary>
        public static string Type_ShowGitHubIssueContactCommand {
            get {
                return ResourceManager.GetString("Type_ShowGitHubIssueContactCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通过此方式向开源项目提出问题.
        /// </summary>
        public static string Type_ShowGitHubIssueContactCommand_Description {
            get {
                return ResourceManager.GetString("Type_ShowGitHubIssueContactCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 访问播客.
        /// </summary>
        public static string Type_ShowPodcastContactCommand {
            get {
                return ResourceManager.GetString("Type_ShowPodcastContactCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通过此方式联系到开发者.
        /// </summary>
        public static string Type_ShowPodcastContactCommand_Description {
            get {
                return ResourceManager.GetString("Type_ShowPodcastContactCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加QQ.
        /// </summary>
        public static string Type_ShowQQContactCommand {
            get {
                return ResourceManager.GetString("Type_ShowQQContactCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通过此方式联系到开发者.
        /// </summary>
        public static string Type_ShowQQContactCommand_Description {
            get {
                return ResourceManager.GetString("Type_ShowQQContactCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发行说明.
        /// </summary>
        public static string Type_ShowReleaseVersionsCommand {
            get {
                return ResourceManager.GetString("Type_ShowReleaseVersionsCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看软件发行说明.
        /// </summary>
        public static string Type_ShowReleaseVersionsCommand_Description {
            get {
                return ResourceManager.GetString("Type_ShowReleaseVersionsCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发送邮件.
        /// </summary>
        public static string Type_ShowSendMailContactCommand {
            get {
                return ResourceManager.GetString("Type_ShowSendMailContactCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通过此方式联系到开发者.
        /// </summary>
        public static string Type_ShowSendMailContactCommand_Description {
            get {
                return ResourceManager.GetString("Type_ShowSendMailContactCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 技术支持.
        /// </summary>
        public static string Type_ShowSupportCommand {
            get {
                return ResourceManager.GetString("Type_ShowSupportCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看技术支持文档.
        /// </summary>
        public static string Type_ShowSupportCommand_Description {
            get {
                return ResourceManager.GetString("Type_ShowSupportCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 官方网址.
        /// </summary>
        public static string Type_ShowWebSiteCommand {
            get {
                return ResourceManager.GetString("Type_ShowWebSiteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看官方网址.
        /// </summary>
        public static string Type_ShowWebSiteCommand_Description {
            get {
                return ResourceManager.GetString("Type_ShowWebSiteCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 技术支持.
        /// </summary>
        public static string Type_SupportOptions {
            get {
                return ResourceManager.GetString("Type_SupportOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看软件技术支持.
        /// </summary>
        public static string Type_SupportOptions_Description {
            get {
                return ResourceManager.GetString("Type_SupportOptions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统设置.
        /// </summary>
        public static string Type_SupportOptions_GroupName {
            get {
                return ResourceManager.GetString("Type_SupportOptions_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 官方网址.
        /// </summary>
        public static string Type_WebsiteOptions {
            get {
                return ResourceManager.GetString("Type_WebsiteOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看官方网址.
        /// </summary>
        public static string Type_WebsiteOptions_Description {
            get {
                return ResourceManager.GetString("Type_WebsiteOptions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统设置.
        /// </summary>
        public static string Type_WebsiteOptions_GroupName {
            get {
                return ResourceManager.GetString("Type_WebsiteOptions_GroupName", resourceCulture);
            }
        }
    }
}
